### ISSUE TITLE
Pasting images into documents clutters CryptDrive root directory

### ISSUE THREAD

**Issue by Raj2032** [xwiki-labs/cryptpad#965] opened 2022-09-04 00:48 UTC
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I would like to request a new feature for CryptPad

- [X] I have searched past issues and labels to check that my question/idea does not exist
- [X] I have understood that this report is dedicated for feature requests, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.

### Summary

The issue is that everytime I want to paste an image inside a document file or a code/markdown file, even though it pastes it into the document/code file, however it would paste it as a file as well in the root directory.

This has made the root directory very messy and I am not too sure why we can't have it just pasted inside the document file? If this is not possible (for whatever reason) why can't the images go inside a hidden folder or something as it is very messy

### Motivation

- Prevent the root directory from being very messy
- Very confusing to distinguish between images I uploaded to the root directory vs images that are for documents/code files, this feature request would prevent this from happening.

**Comment by mthld** [comment] 2022-09-05 07:54
Hello,

This feature already exist, when you paste the image into your document the following pop-up appears:

<img width="517" alt="Screenshot 2022-09-05 at 09 51 26" src="https://user-images.githubusercontent.com/41020854/188397092-5988891f-8d2b-4aa0-a3ba-640e7332236c.png">

If you'd like to, you can uncheck the box "Owned file" and then "Store the file in your CryptDrive". This way the file won't appear on your drive's root directory.

However please note that when you upload non-owned files to CryptPad you loose the ability to delete them later. They will eventually get remove after 90 days of inactivity tho.

Hope this clear things up! :)

**Comment by Raj2032** [comment] 2022-09-05 10:23
@mthld Hey mate thanks for the help, one question, what if I have registered an account, then would it still get removed after 90 days?

**Comment by mthld** [comment] 2022-09-05 10:41
You're welcome!

Having a registered account or not doesn't change this, as long as your document **isn't** stored in your CryptDrive, it will be removed after 90 days of inactivity (no access).

**Comment by Raj2032** [comment] 2022-09-05 10:44
@mthld 

> You're welcome!

:)

> Having a registered account or not doesn't change this, as long as your document isn't stored in your CryptDrive, it will be removed after 90 days of inactivity (no access).

Ok but then can't it stay permanently? Like if I paste an image to the document, then it should stay there for life if I did not choose "Owned file", like wouldn't that make more sense?

**Comment by mthld** [comment] 2022-09-05 11:01
I cannot, the way CryptPad is designed an how files/documents are implemented doesn't allow to works like a standard computer storage.

If the problem is storing attached images in your CryptDrive clutters the root directory, we can maybe think of something improving this. The idea of automatically storing images attached to a document in the same folder has been brought up in the past. Or creating a folder to receive images related to a document. Would that kind of solution works for you?

**Comment by Raj2032** [comment] 2022-09-05 11:06
@mthld I was suggesting to create a "hidden" folder where the images would get stored, that way the user can't see it and no clutter. Is that possible?

**Comment by mthld** [comment] 2022-09-05 13:42
It's not possible at this moment. We aren't sure how that would work UX/UI-wise if someone wants to reuse the uploaded images.

**Comment by Raj2032** [comment] 2022-09-06 08:32
@mthld Oh ok what about just having a special folder named something like `.config` and inside there is where all images are stored?

**Comment by Raj2032** [comment] 2022-09-10 07:34
@mthld THanks mate for taking my idea into consideration :)

**Comment by davidbenque** [comment] 2022-09-14 12:09
Hi @Raj2032 thanks for your feedback. One way to solve this problem would be to have a "destination" setting in the upload dialog, as shown in the quick mockup below. I imagine this would be remembered so you could set an Images folder in your drive for example and have all future uploads stored there by default. I don't think hiding this folder from users is a good idea as there are cases where you might want to see, re-use, or destroy the images. 

![Screenshot of the file upload dialog with a button displaying the destination folder](https://user-images.githubusercontent.com/11028490/190149364-0e68c63a-4462-4aa9-93b6-a5c5cc761df0.png)

There are few issues with this that we would have to solve: how to display a folder picker in the upload dialog, how to deal with cases where users pick a shared folder or team as destination, and so on...

**Comment by mthld** [comment] 2022-10-18 09:17
This is being discussed on the community forum now: https://forum.cryptpad.org/d/15-destination-folder-for-image-uploads

Closing this issue in favor of the forum. :)

**Closed by mthld** 2022-10-18 09:17 UTC
Labels: Feature Request, CryptDrive, UI/UX
