### ISSUE TITLE
Impossible to select part of a string on mobile browsers

### ISSUE THREAD

**Issue by umonaca** [xwiki-labs/cryptpad#435] opened 2019-08-29 03:15 UTC
OS: Android Pie
Browsers: Chrome and Firefox
Pad type: Code and Rich Text (I haven't tested other pad types)

To reproduce, create a pad and randomly type something. Then you will find out that it is impossible to select part of a word, unlike anywhere else on the device.
For example, if you have a long word `ThisIsAVeryLongWord`, you will not be able to select `This`.

**Comment by mthld** [comment] 2022-08-05 13:39
Hi,

I can't reproduce this issue, if it's still happening please create another one. It was probably fixed in the 3 years timeframe behind your report and my answer. :)

**Closed by mthld** 2022-08-05 13:39 UTC
Labels: mobile support, Rich Text
