### ISSUE TITLE
Cant export rich text docs from iPadOS15.3.1's Safari/Firefox

### ISSUE THREAD

**Issue by pherwaniharsh** [xwiki-labs/cryptpad#880] opened 2022-03-10 16:18 UTC
Cant export (download) my rich text documents from either safari or Firefox on ipadOS15.3.1

**Where did it happen?**
The issue occured on CryptPad.fr directly, on a guest use. 

**To Reproduce**
1. Go to CryptPad.fr on Safari/Firefox on an IPad 
2. Rich text Document 
3. Fill the document with some content
4. Go to file menu to export the document, give it a name, choose doc file type and click ok. 

**Expected behavior**
I expected it to either open up the files app for a location where i want it to be downloaded, or atleast give me an indication that it has started downloading it. 

**Screenshots**

 - OS: iPadOS15.3.1
 - Browser: Firefox And Safari 
 - Browser tweaks: firefox "Enhanced Tracking Protection" strict/custom mode.

**Comment by mthld** [comment] 2022-08-05 10:19
Hi,

I can reproduce this issue on iOS v15.6 with a 2nd gen iPhone SE.

**Comment by mthld** [comment] 2022-11-21 14:26
Closing in favor of #973 because this is a wider issue than just Rich Text

**Closed by mthld** 2022-11-21 14:26 UTC
Labels: Bug, Browsers, File Conversion, iOS
