### ISSUE TITLE
Disable localstorage for embedding?

### ISSUE THREAD

**Issue by pheidrias** [xwiki-labs/cryptpad#723] opened 2021-04-27 09:33 UTC
Dear all,

is there any way to not use localstorage? I would like to embed some of your fantastic pads into workadventure, but fail so with getting the message: CryptPad needs localStorage to work. Try changing your cookie permissions, or using a different browser

Interestingly, this message occurs within firefox only, chromium seems to work fine...but I need to get both working...

Thanks in advance,
pheidrias

**Comment by ansuz** [comment] 2021-04-27 10:23
The standard version of Firefox should work normally (it's what I use everyday). What you're experiencing might be related to one of:

* non-standard tweaks to the browser's configuration
* installed extensions
* running a non-standard fork of Firefox (Tor, iceweasel, icecat, ESR, librewolf, cliqz, or any number of browsers that are commonly and erroneously referred to as "Firefox")
  * note: some Linux distributions have been known to provide modified version
* use of a special mode ("Private mode", containers,  enhanced tracking protection)

**Comment by pheidrias** [comment] 2021-04-27 10:46
Hello ansuz,

to be clear: cryptpad is running fine, when I start it "stand-alone" in my browser.
The problem is with _embedding_ (to use it within workadventure) in some sort of iframe.

That is when I do get the above message using firefox but not chrome...

:-(

**Comment by ansuz** [comment] 2021-04-27 11:13
I missed the part about workadventure. I wasn't familiar with the platform, but it seems [they have issues embedding iframes](https://github.com/thecodingmachine/workadventure/issues/517).

I just tested with Firefox by opening a pad that had been embedded in one of my websites with no special configuration, and it works as intended.

**Comment by jnnkB** [comment] 2021-05-09 13:11
Hi, I'm facing the same problem as @pheidrias.

I think the issue you (@ansuz) refereneced hasn't much to do with the problem described since its about rendering iframes inside the map itself. 

What I think @pheidrias referes to is the possibilitiy of opening a website in an iframe like explained [here](https://workadventu.re/map-building/special-zones). This does indeed work in Firefox with the default configuration. But unfortunatly Chromium/Chrome does not work. I think this isn't something specific to WorkAdventure but in newer Chromium versions embedding CryptPad as an iFrame genereally does not work. At least I could not get it to work.

Thanks for your awesome work!

**Comment by ansuz** [comment] 2021-05-10 07:10
> in newer Chromium versions embedding CryptPad as an iFrame genereally does not work. At least I could not get it to work.

The screenshot below demonstrates two separate CryptPad instances embedded in a web page in Chromium (version 90.0.4430.93) on Ubuntu 20.04. The first iframe embeds CryptPad.fr and the second embeds my personal CryptPad instance which is running the example NGINX config.

![Screenshot from 2021-05-10 12-30-02](https://user-images.githubusercontent.com/1264398/117618398-e0f0db00-b13b-11eb-9636-f5853c9ced60.png)

If you can identify _why_ it's being blocked on your side we can investigate further, but without an error message I can only speculate as per my first response.

**Comment by jnnkB** [comment] 2021-05-10 10:10
So I tried it again using Ungoogled Chromium (Version 89.0.4389.114). This is the HTML I used:

```html
<html>
<head>
<style>

iframe {
width: 100%;
height: 100%;
border: none;
}

</style>
</head>
<body>
<iframe src="https://cryptpad.fr/pad/#/2/pad/edit/REMOVED/embed/"></iframe>
</body>

</html>
```

And this is how it looked:

<img width="2046" alt="Screenshot 2021-05-10 at 10 52 06" src="https://user-images.githubusercontent.com/29376715/117633047-f2f36d80-b17d-11eb-875e-5c203274f176.png">

Will try again with a new version of Chromium later today.

**Comment by ansuz** [comment] 2021-05-10 10:55
I just installed ungoogled chromium locally, tested, and can finally reproduce the same behaviour.

Following the recommendation that is displayed in your screenshot I checked ungoogled-chromium's cookie settings. Changing `Chromium settings > Cookies and other site data` from _Block third-party cookies_ to _Allow all cookies_ caused embedded CryptPad iframes to load as expected.

[Ungoogled chromium's readme](https://github.com/Eloston/ungoogled-chromium#objectives) mentions the following:

> ungoogled-chromium features tweaks to enhance privacy, control, and transparency. However, almost all of these features must be manually activated or enabled.

So I suppose this cookie setting is one of those which their development team chose to enable by default.

In any case, I'm going to close this issue since:

1. the displayed alert provides instructions to identify browser configuration errors that block APIs that the platform requires
2. we can't do anything to change configuration on third-party sites intended to block iframes from other domains

**Closed by ansuz** 2021-05-10 10:55 UTC
Labels: More info needed
