### ISSUE TITLE
Double top navbar after registration

### ISSUE THREAD

**Issue by doegox** [xwiki-labs/cryptpad#102] opened 2017-03-31 07:45 UTC
After registration of a new user, I got twice the top navigationbar, see snapshot.
Reloading the page cleared the problem.
I'm using Chromium.

![untitled](https://cloud.githubusercontent.com/assets/60773/24541163/946a86da-15f6-11e7-8c23-d5a6afa2fb6b.png)

**Comment by ansuz** [comment] 2017-03-31 17:35
Thanks for the report.

This looks like a race condition somewhere in the initialization step. I've never seen this myself, but I'll try to reproduce and fix the issue before next release.

**Comment by ansuz** [comment] 2017-04-18 10:36
We were able to reproduce this locally. I believe this issue should be fixed in our next release on April 25th.

**Comment by doegox** [comment] 2017-04-18 12:53
Excellent

**Comment by ansuz** [comment] 2017-04-25 13:40
I'm going to close this as we expect the problem to have gone away. If you experience it again, please let us know.

**Closed by ansuz** 2017-04-25 13:40 UTC
Labels: bug
