### ISSUE TITLE
loss of edits when collaborating on rich text pad

### ISSUE THREAD

**Issue by stragu** [xwiki-labs/cryptpad#388] opened 2019-06-07 12:46 UTC
Hi there

I thought it was important enough to mention here:

I was editing a rich text pad the other day, and edits I had been working on for what I estimate to be 20 to 30 minutes of writing got lost.
There was someone else working on the document at the same time.
I explored the history and the edits were nowhere to be seen; I can 100% confirm that it wasn't the other editor who removed my edits somehow. It just looked like I never wrote any of the text I had been working on for quite a while.

The pad in question is here, if that helps to investigate at all:
https://cryptpad.fr/pad/#/2/pad/edit/zX552vd5pmWHKO-+QI26HP6g/

Has anyone else ever reported something of the sort?

**Comment by tuxayo** [comment] 2019-07-23 09:28
I have a [broken document](https://github.com/xwiki-labs/cryptpad/issues/352#issuecomment-514124473) which recently did something like that to me.

I was adding stuff, which got removed after few seconds. ctrl-z restores it. Then it was removed again.
The JS error were:
```
PREVENTING REMOVAL OF CURSOR 
<span id="5a6748c155d2c3f7bedb6981676dcf08-5625230382252505" class="cp-cursor-position" data-type="" title="name-of-other-person-editing" style="border-color: rgb(124, 9…lor: rgb(124, 93, 215);">
inner.html:37:21
    error jQuery
    preDiffApply https://cryptpad.fr/pad/cursor.js?ver=2.25.0-5:20
    preDiffApply https://cryptpad.fr/pad/inner.js?ver=2.25.0-5:225
    applyDiff https://cryptpad.fr/bower_components/diff-dom/diffDOM.js?ver=2.25.0-5:1166
    apply https://cryptpad.fr/bower_components/diff-dom/diffDOM.js?ver=2.25.0-5:1138
    apply https://cryptpad.fr/bower_components/diff-dom/diffDOM.js?ver=2.25.0-5:1137
    andThen2 https://cryptpad.fr/pad/inner.js?ver=2.25.0-5:615
    fire https://cryptpad.fr/common/common-util.js?ver=2.25.0-5:32
    fire https://cryptpad.fr/common/common-util.js?ver=2.25.0-5:32
    contentUpdate https://cryptpad.fr/common/sframe-app-framework.js?ver=2.25.0-5:185
    onRemote https://cryptpad.fr/common/sframe-app-framework.js?ver=2.25.0-5:206
    nThen https://cryptpad.fr/bower_components/nthen/index.js?ver=2.25.0-5:37
    nThen https://cryptpad.fr/bower_components/nthen/index.js?ver=2.25.0-5:67
    onRemote https://cryptpad.fr/common/sframe-app-framework.js?ver=2.25.0-5:205
    start https://cryptpad.fr/common/sframe-chainpad-netflux-inner.js?ver=2.25.0-5:63
    pushUIPatch https://cryptpad.fr/bower_components/chainpad/chainpad.dist.js?ver=2.25.0-5:1240
    pushUIPatch https://cryptpad.fr/bower_components/chainpad/chainpad.dist.js?ver=2.25.0-5:1240
    handleMessage https://cryptpad.fr/bower_components/chainpad/chainpad.dist.js?ver=2.25.0-5:1508
    message https://cryptpad.fr/bower_components/chainpad/chainpad.dist.js?ver=2.25.0-5:1712
    start https://cryptpad.fr/common/sframe-chainpad-netflux-inner.js?ver=2.25.0-5:118
    on https://cryptpad.fr/common/outer/worker-channel.js?ver=2.25.0-5:85
    create https://cryptpad.fr/common/outer/worker-channel.js?ver=2.25.0-5:155
    create https://cryptpad.fr/common/outer/worker-channel.js?ver=2.25.0-5:154
    fire https://cryptpad.fr/common/common-util.js?ver=2.25.0-5:32
    fire https://cryptpad.fr/common/common-util.js?ver=2.25.0-5:32
    create https://cryptpad.fr/common/sframe-common.js?ver=2.25.0-5:533


uncaught exception: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data boot2.js:46:9
    onerror https://cryptpad.fr/common/boot2.js?ver=2.25.0-5:46


SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data worker-channel.js:142:29
    create https://cryptpad.fr/common/outer/worker-channel.js?ver=2.25.0-5:142
    fire https://cryptpad.fr/common/common-util.js?ver=2.25.0-5:32
    forEach self-hosted:266
    fire https://cryptpad.fr/common/common-util.js?ver=2.25.0-5:32
    whenReady https://cryptpad.fr/common/sframe-common-outer.js?ver=2.25.0-5:116

```
Updating the page solved the issue.

**Comment by frlen123** [comment] 2019-08-05 18:18
Yesterday, after some hours editing a Rich Text pad, I realized that all my last edits were **not** saved. This possibly could have been the work of some hours, I still don't know how much was lost, though I can see it's already a lot. 

Is there a way to manually force a save, such as pressing Ctrl+S? I can't keep using Cryptpad if there's no such option

**Comment by mthld** [comment] 2022-08-05 13:37
Hello,

This kind of issues would me mostly caused by web browser incompatibilities. Please see the "Common issues" section of your documentation FAQ: https://docs.cryptpad.fr/en/FAQ.html#common-issues

Since this issue is 3 years old, I'll be closing it now. Don't hesitate to reopen one if needed.

**Closed by mthld** 2022-08-05 13:37 UTC
Labels: browser support, Rich Text
