### ISSUE TITLE
Try to delete Kanban entry in shared folder results in hanging process (timeout)

### ISSUE THREAD

**Issue by ebbomuc** [xwiki-labs/cryptpad#542] opened 2020-05-06 08:04 UTC
Used Firefox or Brave on mac OSX:
1) Created Kanban in shared folder
2) tried to delete it by clicking on delete button
3) program hangs have to close window (timeout)
4) have to reload drive page several times
5) still problem - cannot delete entry

**Comment by ansuz** [comment] 2020-05-06 16:10
Hi,
I'm not able to reproduce in Firefox (mainline or nightly) or chromium. I tried deleting a kanban in a shared folder via all the deletion methods (keyboard, toolbar button, right-click).

Is it one particular kanban that you've tried to delete, or can you reproduce these steps with _any kanban_ ?

**Comment by ebbomuc** [comment] 2020-05-06 20:42
Hi,
I can reproduce with any kanban. I remember that yesterday a message came up that system needs to be updated. I know that it was working before. It also happens if I try to delete while try to open with the shared link on another computer.

**Comment by ebbomuc** [comment] 2020-05-07 08:05
Hi, do not know if something has been changed overnight (live in europe) but just been able to delete - everything worked as expected after 2 days with problem. Thank you.

**Comment by ansuz** [comment] 2020-05-07 15:16
That's mysterious, but I'll close this issue for now. If the problem re-occurs feel free to re-open.

**Closed by ansuz** 2020-05-07 15:16 UTC
Labels: More info needed, bug
