### ISSUE TITLE
In Presentation mode: Deactivate information box

### ISSUE THREAD

**Issue by mp-4** [xwiki-labs/cryptpad#491] opened 2020-01-22 19:56 UTC
**Problem**
At the presentation using the URL-Presentation mode-Link, it always displays an "info box" when someone is opening oder closing the pad.

"<XYZ> is leaving the session" - (or something like this) 

This disturbs the lecture and distracts the audience.

**Solution:**
Checkbox to hide these messages.
OR
Deactivate these messages completely in presentation mode.

**Enviroment**
Cryptpad-Version 3.9.0

**Comment by ansuz** [comment] 2020-02-27 15:07
I just tested this on cryptpad.fr (v3.12.0) and I can't reproduce. Maybe we've fixed in the meantime and didn't take note of it.

**Closed by ansuz** 2020-02-27 15:07 UTC
