### ISSUE TITLE
Kanban color picker is constantly in the way  😞

### ISSUE THREAD

**Issue by theysayitislife** [xwiki-labs/cryptpad#277] opened 2018-09-26 20:30 UTC
Hi - there seems to be a new feature that allows you to pick a color for each individual card in the Kanban board, but it has a major problem...

Every time I try to drag the card to move it (which I do constantly) the color picker pops up and completely gets in the way.

Unfortunately the Kanban board (which I love so dearly) is no longer functional because if this minor UX issue.

It would be an easy fix to just revert as it was before the card color picker, which seems like it could be helpful I guess, but it's certainly not worth having when it's blocking the cards from being usable at all.

Thanks so much for the great work on this, I don't mean to sound grumpy but it's killing my whole workflow which I've come to love with your tools   :)

**Comment by ansuz** [comment] 2018-09-27 12:33
Hi,

What you're describing sounds like an easy problem to fix, but I can't reproduce that behaviour with either Firefox or Chromium.

Can you please share the details of the platform where you're experiencing the issue (browser and version, operating system, and any plugins that you might have installed)?

**Comment by ansuz** [comment] 2018-09-27 12:39
@MTRNord you might be interested in this thread if you're using jscolor for anything else.

**Comment by theysayitislife** [comment] 2018-09-27 17:14
Thanks for your response!

I'll have to find time to record a quick screen video to show you, it's hard to describe otherwise.

The issue came up on Ubuntu 16.04 with Firefox 62, naked profile with zero addons. I can try to get my hands on a more common machine like a Mac to see if it still persists there

**Comment by MTRNord** [comment] 2018-09-27 17:54
I did think I fixed that before the merge. This is basicly a click event which shouldn't get triggered when dragging. :/ JS ztiggers a click event and drag event which causes the color picker to pop up when scroling :( I could only start fixing it at the end of this weekend

**Comment by ansuz** [comment] 2018-10-23 17:07
This bug was fixed in today's release.

**Closed by ansuz** 2018-10-23 17:07 UTC
Labels: bug
