### ISSUE TITLE
Conflicting edition

### ISSUE THREAD

**Issue by hellekin** [xwiki-labs/cryptpad#46] opened 2016-10-10 09:19 UTC
On our deployment of cryptpad, there's a glitch with the cursors being confused when more than one person are editing at the same time: this results in conflicting editions where letters are sent to the wrong line, erasure removes letters from another line, etc.

This may be related to #42, however I'd like to know if other people bumped into this, and if there's a way to work around it.  What information would help to debug? (I didn't make the installation, so I need to delegate the replies.)

**Comment by ansuz** [comment] 2016-10-10 09:41
This has come up a few times (though maybe not as github issues).

The problem is related to our operational transformation algorithm, and I'm actively working on it.

Fortunately, it should be solved soon, but unfortunately it's a complicated problem, and I'm going to have to test it very thoroughly before merging.

While I'm hesitant to give a time estimate, I think it should be fixed in another week or two. I'll update this issue as progress is made (and available for testing in a branch).

**Comment by pojebunny** [comment] 2016-12-07 08:04
I can confirm that at least CTRL-Z works globally.
If you write something, then someone adds text in a different line and you try to CTRL-Z your text, you will first delete other users writing.

**Comment by ansuz** [comment] 2018-11-27 12:51
This issue has been here a while, and we finally believe we have a fix. We'll include it in the next release.

**Closed** 2018-11-27 17:15 UTC
Labels: bug, fixed in staging
