### ISSUE TITLE
CryptDrive(Sheets): fails to export as both xlsx or bin

### ISSUE THREAD

**Issue by niartenyaw** [xwiki-labs/cryptpad#664] opened 2020-12-16 01:21 UTC
can not export cryptpad sheet in any of the provided formats.

**Where did it happen?**
CryptPad.fr

**To Reproduce**
1. under the `File --> Export` menu
2. Export as either bin or xlsx
3. See that nothing is downloaded on the browser

**Expected behavior**
A file should be downloaded by the browser.

**Screenshots**
There is some output in console when choosing `xlsx` but not `bin`. this is the top of the output.
<img width="500" alt="Screen Shot 2020-12-15 at 5 18 50 PM" src="https://user-images.githubusercontent.com/8084693/102292353-d79b7380-3ef9-11eb-8cb5-555bb0369210.png">

**Browser (please complete the following information):**
 - OS: macOS Catalina
 - Browser firefox nightly 84.0a1
 - Extensions installed: none (UBlock Origin, Adblock Plus]
 - Browser tweaks: none

**Additional context**

**Comment by ansuz** [comment] 2020-12-24 09:41
Hi,

I'm able to export to either format as expected using Firefox 84.0, Firefox nightly 80.0a1, and Chromium 87.0.4280.66. All of these were tested on Ubuntu so it's possible this bug only affects macOS Catalina. Unfortunately I'm not able to test on Catalina.

**Comment by ansuz** [comment] 2021-05-06 06:42
We've fixed a number of possible errors since this was reported, so I'm going to close this. If you can still reproduce on CryptPad.fr please respond and I'll be happy to reopen. It's worth testing with your adblockers disabled, however. UBlock Origin is fairly reliable, but Adblock Plus has been known to cause problems, and running two adblockers in parallel is likely to contribute to incorrect behaviour.

**Closed by ansuz** 2021-05-06 06:42 UTC
Labels: spreadsheets
