### ISSUE TITLE
Pad stops loading after Update to 3.17.1

### ISSUE THREAD

**Issue by GerJuli** [xwiki-labs/cryptpad#550] opened 2020-05-18 19:12 UTC
All existing and new created Pads fail to load for Firefox and Chromium after update of Cryptpad to 3.17.1. 

The consol logs 
```
callExtract: undefined
callLine: NaN
column: 12
extract: Array(3) [ "        div.cp-comment-bubble {", "            .buttons_main();", "            position: relative;" ]
filename: "/pad/app-pad.less"
index: 1744
line: 74
message: "variable @variables_input-height is undefined"
stack: undefined
type: "Syntax"
<prototype>: Object { constructor: R(e, t, n), toString: toString(e)
, stack: "" }
LessLoader.js:170:49
```

The issue occures on pad.gartensia.de

1. Go to pad.gartensia.de
2. Create a Richt Text document
3. See error in cosol log

Example existing pad: https://pad.gartensia.de/pad/#/2/pad/edit/+aq0TfCt-vFUBBCEzT-20fH1/

I hope to have old documents accessible again.

**Browser:**
 - OS: Ubuntu 20.04 + Android
 - Browser: Firefox  [Ubuntu: Firefox 76.0.1 (64-bit) + Android], Chromium [Ubuntu]
 - Extensions installed: None/Deactivated
 - Browser tweaks:

**Comment by GerJuli** [comment] 2020-05-19 05:54
I had to use my backup, as users are dependent on the server. So now everything works (on the old version). I will try to reproduce this in a test environment when I have the time.
Update of versions was from 3.5.0 -> 3.17.1

**Comment by ansuz** [comment] 2020-05-29 17:49
The error message suggests it's an error in a stylesheet (referencing a variable that does not exist). Have you customized the styles on your instance? If so, I'd suggest testing installing the latest version in a staging environment without your custom changes and gradually reintroducing them to see what breaks it.

**Comment by ansuz** [comment] 2020-06-03 19:10
I'm going to close this since there doesn't seem to be anything actionable on our side. Feel free to re-open if you can isolate the cause.

**Closed by ansuz** 2020-06-03 19:10 UTC
Labels: More info needed, configuration
