### ISSUE TITLE
Problems with view mode when sharing (spreadsheet, version 3.17)

### ISSUE THREAD

**Issue by dafqs** [xwiki-labs/cryptpad#543] opened 2020-05-08 19:20 UTC
**Describe the bug**
The display is incorrect when sharing sheets (incomplete). The problem occurs with version 3.17.

**Where did it happen?**
The problem occurs with different instances when using 3.17. (for example cryptpad.fr).

**To Reproduce**
1. Go to spreadsheet (Tabelle)
2. Share (Teilen)
3. View Mode (Ansicht)
4. Preview (Vorschau)

**Expected behavior**
Complete display of the current pad in view mode.

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 81.0.4044 - The same behavior with Opera 68.0.3618.63

![fehler1](https://user-images.githubusercontent.com/65040381/81466333-1c776300-91d1-11ea-9fa9-4c5ab37b17c4.png)
![fehler2](https://user-images.githubusercontent.com/65040381/81466334-1d0ff980-91d1-11ea-975f-c4e3d4528e21.png)

**Comment by alfkoehn** [comment] 2020-05-09 09:25
Same problem here with Firefox 75.0 (64-bit)

**Comment by ansuz** [comment] 2020-06-08 15:56
This issue has been partially addressed. It was caused by our use of an OnlyOffice API to disable editing which also prevented older history from being inserted into the interface when connecting. As of 3.18.0 the correct content should be displayed when first loading the document.

Unfortunately, once users have loaded the document's history we still have to lock it to prevent them from editing it. As a result, modifications made to the document by remote editors while you are in view mode will not be applied. We're looking for a solution to this problem and hope to have something in place for our 3.19.0 release.

**Comment by ansuz** [comment] 2020-06-19 16:51
We tried a number of possible solutions to actively display the latest data, but they all introduced other issues. We now have a system in place (in our `staging` branch) which prompts users to click a button which triggers a reload of the OnlyOffice editor (not the full page). The prompt is displayed when remote users make changes after a short delay to avoid spamming the viewer while series of changes are being made.

**Comment by ansuz** [comment] 2020-06-19 16:51
We plan to deploy this update next week as a part of our 3.19.1 minor release.

**Comment by ansuz** [comment] 2020-06-23 20:11
Closing now that we've tagged and deployed [3.19.1](https://github.com/xwiki-labs/cryptpad/releases/3.19.1)

**Closed by ansuz** 2020-06-23 20:11 UTC
Labels: fixed in staging, spreadsheets
