### ISSUE TITLE
Changing style move the cursor to top of the text

### ISSUE THREAD

**Issue by elecharny** [xwiki-labs/cryptpad#296] opened 2018-11-27 09:30 UTC
When you select a snippet of text and change its style, you get back to the top of the text, which is a big painfull if you are dealing with a long text. I'd rather expect to have the focus stay on the selected snippet.

This does not happen when you click on Bold/Italic/Underline icons. Only when you select one of the four dropdown menus (Style, format, font, size)

**Comment by ansuz** [comment] 2018-11-27 10:06
Hi @elecharny,

I'm not able to reproduce your issue.

1. Are you experiencing this problem on cryptpad.fr or some other instance?
2. If some other instance, can you report the version?
  * you'll find it in the `/about.html` page
3. what browser are you using?
  * what version of that browser are you using?

Thanks

**Comment by elecharny** [comment] 2018-11-27 11:15
Hi @ansuz,

Sorry, I should have provided a bit of context...

I'm using it on cryptpad.fr, on a Firefox 63.0.3 version.

I have tested it on Safari 12.0.1 and Chrome 70.0.3538.102, and it's working just fine on those browsers.

So it seems to be a FF related issue.

**Comment by ansuz** [comment] 2018-11-27 13:00
Interesting. I was running the same version of firefox when I tried to reproduce it. Since you tested on safari as well I suppose you're using a Mac?

**Comment by ansuz** [comment] 2018-11-27 13:04
Nevermind, we were able to reproduce, it's just intermittent.

**Comment by ansuz** [comment] 2018-11-27 13:08
Fixed in [this commit](https://github.com/xwiki-labs/cryptpad/commit/cc3e6f39246ffecb42fbf8067bf10444e6d7d2df)

**Comment by elecharny** [comment] 2018-11-27 13:36
Awsome !

Yes, I'm using a Mac, High Sierra 10.13.6.

FTR, it's not intermittent for me.

**Closed** 2018-11-27 17:15 UTC
Labels: fixed in staging
