### ISSUE TITLE
Rich text view mode: comment button visible, but not functional

### ISSUE THREAD

**Issue by hartenfels** [xwiki-labs/cryptpad#570] opened 2020-06-25 14:35 UTC
**Describe the bug**
When viewing a rich text pad via its view link, selecting some text in the pad gives the option to add a comment for the selected text, either by clicking on the speech bubble next to the pad or via the right-click menu. Attempting to actually click on either of those buttons does nothing.

**Where did it happen?**
In rich text pads on cryptpad.fr.

**To Reproduce**
1. Create a rich text pad and write some text in it.
2. Grab the view link and open it.
3. Select some of the text in the pad.
4. Attempt to add a comment by
4.1. EITHER Clicking on the speech bubble icon that appears on the right
4.2 OR right clicking on the selected text and choosing "Comment" in the dropdown,
5. Observed behavior: the pad slides to the left to make room for the comment input box, but no such box appears. The selected text does not get highlighted either. Further clicks on the comment button do nothing at all.

**Expected behavior**
Option 1: the button should _not_ be visible in view mode because, as a viewer, I can't add comments.
Option 2: clicking the button should actually let me add a comment as a viewer. (I'd personally prefer this option, but I can imagine that it's not possible since it modifies the document.)

**Platforms:**
I reproduced the issue on:
* Arch Linux, Firefox 77.0.1 (64-bit) with UBlock Origin
* Android 9, Firefox 68.9.0, UBlock Origin
* Android 9, Chrome 83.0.4103.106, no addons

**Comment by ansuz** [comment] 2020-06-25 18:40
The intended behaviour is the _Option 1_ which you described. I've pushed a fix to our staging branch which disables the contextmenu entry for comments as well as the button which appears to the right of the document. We'll merge and deploy the fix in our upcoming 3.20.0 release.

**Comment by hartenfels** [comment] 2020-06-27 13:42
Thank you for the fast response and fix!

**Closed** 2020-07-07 20:46 UTC
Labels: bug, fixed in staging
