### ISSUE TITLE
Used space reported incorrectly

### ISSUE THREAD

**Issue by mxs975** [xwiki-labs/cryptpad#318] opened 2019-02-05 12:27 UTC
Hi,
I'm just trying to see if I could switch from using Google Sheets to CryptPad.
I have created 1 spreadsheet with a couple of worksheets in it. 
When I right-click on the file and chose "Properties" it says that the size is 23.2KB. 
I have downloaded the same spreadsheet from my Google Drive in both OpenDocument (ods) and Excel (xlsx) format. The xlsx is 52.6KB, the ods is 33.9KB.
No pictures or anything else in these, only text and numbers.
This is the only file I have on CryptPad, and I have an empty folder created as well. 
Emptied the "Trash" as well.
Yet CryptPad says that I'm using 5.95 / 50 MB??

![image](https://user-images.githubusercontent.com/40632444/52273226-1d23a880-2941-11e9-983d-836c879fe6fc.png)
![image](https://user-images.githubusercontent.com/40632444/52273271-3b89a400-2941-11e9-9730-872f1a33f5d7.png)

**Comment by yflory** [comment] 2019-02-05 16:02
Hi, The difference between your CryptDrive size (5.95MB) and your spreadsheet size (23.2KB) is caused by 2 elements:

First, there was a bug in the size displayed in the "Properties" box for spreadsheets. The size displayed was smaller than what it was on our servers. This issue will be fixed in the next release (probably next Tuesday)
The spreadsheet should have a size close to the xlsx and ods formats, but we're also storing the entire encrypted history of all the changes. The history is not used at the moment (this application is still in development) but we hope to have this feature working at some point.

The second element is the size of your CryptDrive and its history. It is also stored as encrypted data on the server and its size is included in the total. The CryptDrive history can be used to recover documents deleted by accident from your drive.

We are aware that the CryptDrive history can use a lot of space for active and/or long-time users. We plan to add a way to clear this history for users that don't need it (and also the pads/spreadsheets history if you're the owner) in the near future.

**Comment by mxs975** [comment] 2019-02-06 13:10
Many thanks! Today it looks better (showing 0.24/50MB).
Unfortunately I cannot open the spreadsheet though, it gets stuck at "Loading spreadsheet" (Tried the latest Google Chrome which I haven't used before to access Cryptpad and the latest Firefox which I have used previously. Also tried to delete the cache but it didn't help...) But it's probably another issue (and should be reported separately)

**Comment by ansuz** [comment] 2019-02-12 13:18
This issue should be fixed with today's release.

**Closed by ansuz** 2019-02-12 13:18 UTC
Labels: question
