### ISSUE TITLE
Teams "error" & Not Loading

### ISSUE THREAD

**Issue by tizzler1234** [xwiki-labs/cryptpad#663] opened 2020-12-15 07:24 UTC
**Describe the bug**
When I go to the teams page, I then click OPEN under my team name. A small red box in the bottom left corner of the screen that reads "error" appears. Then nothing attempts to load. We recently onboarded a couple dozen new people from our organization onto the team and we are now experiencing this issue. We only have the one account as the admin so this is a big problem for us being able to shift over to cryptpad.

**Where did it happen?**
 CryptPad.fr 

**To Reproduce**
1. Log into account
2. Click teams in top righthand drop down
3. Click "open" on team name

**Expected behavior**
My team should appear as normal and I should be able to access my files.

**Screenshots**

**Browser (please complete the following information):**
 -  iOS]
 -

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: 
 -  safari]

**Additional context**

**Comment by mchubby** [comment] 2020-12-18 12:15
I have the same on a dockerized nightly build from 4 days ago (I know, it's not a supported case)

In data/logs/*.ndjson, there are entries like

```
["ERROR", "timestamp", "HK_PARSE_ERROR",{"message":"SyntaxError","input":"always the same string for all team invite links starting with DCr16e",1608280183911]"}]
```
it's hard to tell where it's occurring b/c no stack trace.

- When it happened to a teammate, I logged out and back in and then I couldn't reopen the team ("ERROR" in the bottom-left corner).

- I had another admin kick me out from the team and send a new invite, but had the same error while decrypting the invitation ("ERROR" in the bottom-left corner).

**Comment by ansuz** [comment] 2020-12-24 10:03
Sorry for the silence here. We followed up via a support ticket on cryptpad.fr.

@mchubby it would be helpful to know what branch your build is/was targeting. It's somewhat unlikely the issue was related to the server, however, restarting would have updated the client's cache-busting version string which would have caused newly opened tabs to spawn a new shared-worker on each connected client. Shared workers persist in the background as long as any tabs that requested them remain open. You should also be able to load a fresh shared-worker by:

1. closing and re-opening the browser entirely
2. closing all tabs connected tabs and opening a new one
3. clicking the "flush cache" button on the instance admin panel and opening a new tab
4. connecting via a different browser or private/incognito session

**Comment by roland68500** [comment] 2021-03-25 09:41
I have the same problem : 
I cannot create teams on my own pad or on new pads created !

**Comment by ansuz** [comment] 2021-05-06 07:07
I'm going to close this as we've applied a number of fixes to address this problem since the original issue. @roland68500 if the problem is still occurring for you please create a new issue and provide the information that's requested in the issue template.

**Closed by ansuz** 2021-05-06 07:07 UTC
