### ISSUE TITLE
Safari 9.1.2 /code part of the document is off screen

### ISSUE THREAD

**Issue by cjdelisle** [xwiki-labs/cryptpad#226] opened 2018-02-08 11:31 UTC
Only 17 lines of a 25 line doc are displayed

probably related to:
div.codeMirror-scroll
and height: 100%

**Comment by cjdelisle** [comment] 2018-02-08 11:32
Bug not present in 11.0.3 (latest)

**Comment by ansuz** [comment] 2018-10-18 08:16
Closing as it seems the issue is no longer reproducible.

**Closed by ansuz** 2018-10-18 08:16 UTC
