### ISSUE TITLE
Sheets, filter, sort & table feature not working

### ISSUE THREAD

**Issue by tizzler1234** [xwiki-labs/cryptpad#660] opened 2020-12-12 08:11 UTC
**Describe the bug**

When I highlight an area and click the sort function nothing happens, even when the entire area is numbers, and then when all laters aswell. Likewise, nothing happens when I click filter. When I go to make a table it also no longer appears. Even after logging out and logging back in, I have the same issue.

**Where did it happen?**
it happened on cryptpad.fr on firefox, chrome, mac and PC.

**To Reproduce**
1. Go to "cryptpad.fr"
2. Click on sheets, inputs some data fields, highlight them then click on the filter or sort icon. 
3. See error as nothing happens

**Expected behavior**
I should see a new table format appear when clicking on the table feature. Or when sorting my items should fall in order alphabetically. Likewise when clicking the filter tab I should see a small dropdown box to click on how to filter.

**Screenshots**

**Browser (please complete the following information):**
 - OS: MAC and PC
 - Browser firefox, chrome, safari, edge, 
 

**Additional context**

**Comment by smokyblisters** [comment] 2020-12-28 20:59
Yes. This feature is broken for existing spreadsheets, too. As in, spreadsheets that previously had filters set up no longer respond to filter functions. 

Not sure it's related, but I first noticed this breaking around the same time CP had to migrate servers a few weeks ago due to a physical malfunction.

**Comment by sysfu** [comment] 2021-01-18 00:57
Reproduced this using using latest version of Brave on both Elementary OS Hera 5.x and macOS 10.15.7

**Comment by smokyblisters** [comment] 2021-02-03 18:41
Any update here? This is making your service unusable for spreadsheets. Pretty frustrating.

**Comment by ansuz** [comment] 2021-03-04 03:50
Sorting and filtering is fixed in our [4.2.0 release](https://github.com/xwiki-labs/cryptpad/releases/4.2.0). The issue was unrelated to December's server migration.

**Closed by ansuz** 2021-03-04 03:50 UTC
Labels: fixed in staging, spreadsheets
