### ISSUE TITLE
Feature Request: Suggesting Edits/Track Changes

### ISSUE THREAD

**Issue by jnnkB** [xwiki-labs/cryptpad#717] opened 2021-04-19 20:07 UTC
It would be really cool to have an Suggesting Edits/Track Changes mode in Rich Text. This could greatly improve collaboration in cryptpad.

**Comment by ansuz** [comment] 2021-05-06 07:03
I'm going to close this as a duplicate of #248

**Closed by ansuz** 2021-05-06 07:03 UTC
Labels: feature request

**Comment by jnnkB** [comment] 2021-05-06 17:54
Sorry. Don't know why I didn't find it.
