### ISSUE TITLE
Request: add outline to Rich Text Pad

### ISSUE THREAD

**Issue by karroffel** [xwiki-labs/cryptpad#243] opened 2018-05-02 18:28 UTC
The Rich Text editor is really nice for working together with other people, but when the documents gets bigger there is a lot of scrolling involved and there is no top-level overview of the whole document.

In Google Docs this is solved by the document *outline*.

![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FLQGFMIx9lBo%2Fmaxresdefault.jpg&f=1)

It would be really nice if this would be added, no other FOSS collaborative text editor supports that as far as I know and I miss it a lot.

**Comment by ansuz** [comment] 2019-12-05 17:29
I'm closing this as a duplicate of [#399](https://github.com/xwiki-labs/cryptpad/issues/399) even though it's newer as that issue is more visible.

We plan to add this but I'm not sure exactly when to expect it.

**Closed by ansuz** 2019-12-05 17:29 UTC
Labels: feature request
