### ISSUE TITLE
destroying a shared folder does not destroy its content

### ISSUE THREAD

**Issue by martinetd** [xwiki-labs/cryptpad#605] opened 2020-09-01 18:31 UTC
**Describe the bug**
destroying a shared folder does not clean up its content

**Where did it happen?**
self-owned instance (3.20.1) I just setup.

**To Reproduce**
1. Go to drive
2. Create a new shared folder, enter it
3. Upload a file there, watch it appear in the blob directory of the server (I used a relatively big file and `find -type f -size +500k`)
4. Go back to parent folder and destroy shared folder
5. Notice the file is still there in blobs

**Expected behavior**
Doing the same with a non-shared folder (moving it to trash and destroying from trash) moves the blob file to 'archive'; I would expect this to do the same given the shared folder itself is no longer accessible ("This pad has been deleted by its owner and is no longer available." message when trying to access the shared url)

I guess some crontab might clean this up later but I don't see how (is there any way of knowing what files are pointed at by folders? I would assume folder content is encrypted as well, so this can only be done when the user acts on it)

Thanks!

**Comment by mthld** [comment] 2022-08-08 08:35
Hello,

Is this issue still occurring on CryptPad latest version? `v5.0`? As of today we can't reproduce this from our end.

**Comment by martinetd** [comment] 2022-08-10 10:17
nixpkgs is pretty far behind on cryptpad version right now, so I'm stuck on 4.11 from last year.
I'd very much like to upgrade and confirm but it's been a thorn on my side for a while so I can make no promise of a timeframe -- but I've made a note to retest when I do upgrade. Sorry.

I'll update this ticket when I do, but in the meantime I'd be happy to close the issue and take your word for it -- please say.

(Oh, actually it was so out of date that it just got removed last month. . . The version in there depended on an obsolete version of nodejs... Well, doesn't change the work required to upgrade anyway; bower is quite difficult to work with in the nix world for some reason)

**Comment by mthld** [comment] 2022-08-11 09:54
Alright, I'll close this issue then. Don't hesitate to come back and share any feedback if needed!

**Closed by mthld** 2022-08-11 09:54 UTC
Labels: CryptDrive
