### ISSUE TITLE
Shift + wheel does not seem to horizontal scroll

### ISSUE THREAD

**Issue by carimura** [xwiki-labs/cryptpad#568] opened 2020-06-23 15:30 UTC
**Describe the bug**
On a Mac (maybe on Windows too but I only use a Mac), many sites including GDrive allow horizontal scroll by pressing shift and using the mouse wheel. This does not seem to be supported with Cryptpad. In spreadsheets, it's extremely useful.

It does work in Chrome though.

**Where did it happen?**
CryptPad.fr

**To Reproduce**
just press shift and use the wheel :) 

**Expected behavior**
horizontal scrolling

**Screenshots**

**Browser (please complete the following information):**
 - OS: OS X Mojave
 - Browser Firefox (Works in Chrome)
 - Version 77.0.1
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]
 - Browser tweaks: tried incognito with no plugins and still doesn't work

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ansuz** [comment] 2020-06-23 16:18
I just tested on Ubuntu 16.04 and Firefox@77.0.1, where it works as expected, so it's thankfully not a matter of it not being supported in OnlyOffice. We'll test on some different OS/browser combos when we get the chance. Thanks for the report!

**Comment by ansuz** [comment] 2021-04-27 10:09
We haven't been able to reproduce this and noone else has reported this in some time. It might have been an intermittent issue in a particular version of Firefox or something caused by one of your extensions. I'll close this for now. If you have more information or if you can narrow it down to occurring when a particular extension is present we'll take another look.

**Closed by ansuz** 2021-04-27 10:09 UTC
Labels: spreadsheets
