### ISSUE TITLE
Can't access my account anymore: teams stuck at 30% while loading

### ISSUE THREAD

**Issue by Zughy** [xwiki-labs/cryptpad#703] opened 2021-03-15 11:23 UTC
**Describe the bug**
While logging in, it remains stuck on "Load Teams (30%)"

**Where did it happen?**
cryptpad.fr

**To Reproduce**
Log-in

**Expected behavior**
I can log-in

**Browser (please complete the following information):**
 - OS: Fedora 33 workstation
 - Browser: Firefox 86.0
 - Extensions: uBlock Origin, Cookie AutoDelete, Canvas Blocker, LocalCDN, HTTPS Everywhere, ClearURLs
 - Browser tweaks: privacy-hardened. Strict mode, no WebRTC

**Additional context**
Yesterday a friend of mine created a team, where I joined (2 teams out of 5) and where I created / loaded a few files. I've also tried to turn off uBlock Origin but it doesn't change anything

P.S.: I love your project

**Comment by jackt1613** [comment] 2021-04-12 04:12
Same here, I can reproduce the problem.

**Comment by ansuz** [comment] 2021-04-12 13:45
@Zughy: sorry for the delayed response! Somehow I missed the original notification for this issue.

@jackt1613: thanks for bringing this to my attention!

It's possible your browser has cached some invalid data for your team and is failing to load because of that. We've added many guards against this but it's possible we missed an edge case.

You  can try to clear your cache by visiting https://cryptpad.fr/logout/, which will automatically clear the relevant cache and redirect you to the login page.

Please let us know if this helps as it will confirm whether the cache was to blame for this behaviour.

**Comment by jackt1613** [comment] 2021-04-12 15:00
@ansuz Tried to log out, couldn’t solve the problem. The team was removed from the other account and my account functions normally again.

**Comment by ansuz** [comment] 2021-05-06 06:44
Thanks for the update @jackt1613. We implemented some fixes in the meantime that helped another user with a similar problem. I'm going to close this since I believe everyone in this thread has had normal behaviour restored one way or another.

**Closed by ansuz** 2021-05-06 06:44 UTC
