### ISSUE TITLE
Spreadsheets not saving properly

### ISSUE THREAD

**Issue by hentai-kamen** [xwiki-labs/cryptpad#395] opened 2019-06-26 04:36 UTC
I am working with spreadsheets, and they aren't saving and loading properly. I would do work, and it would all be gone and go to a previous version. Not sure what is going on.

**Comment by AndrewJ-Cpad** [comment] 2019-09-13 17:22
I had the same issues.  In the end I abandoned the spreadsheet (it is truly beta).  It would shuffle data around in the sheet in very strange ways when a document was reopened.

**Comment by ansuz** [comment] 2020-01-22 18:37
We've since fixed a number of issues in our spreadsheet integration and taken the editor out of beta status. I'm going to close this issue for now since I'm not able to reproduce the behaviour you've mentioned. If you continue to experience problems please re-open this or make a new issue.

**Closed** 2020-01-22 18:37 UTC
Labels: spreadsheets

**Comment by RandianHero** [comment] 2020-06-27 05:10
The issue still exist. Having document roll back, add rows and overwrite weirdly while using sheets in opera. I tried Chrome to see if it was a browser issue but it still remains.
