### ISSUE TITLE
Focus loss on CryptPoll with Chromium

### ISSUE THREAD

**Issue by doegox** [xwiki-labs/cryptpad#103] opened 2017-04-03 11:18 UTC
Hi, using Chromium, I can't edit fields of a CryptPoll.
As soon as one char is typed, the field is not in focus anymore, even when clicking on it again.
Basically the only way that works is copy/paste.
I tried also on a Chromium Incognito session with all extensions disabled, same issue.
Changing title or description works fine, only editing the table names or options fields has the issue.

Under Google Chrome I've no issue.
Under Firefox I've no issue.

**Comment by ansuz** [comment] 2017-04-03 13:56
@cjdelisle is apparently able to reproduce on Chrome for Mac (version 57), while every other browser works.

We have another macbook at the office which seems to work well, which is running v56. I'm updating it now to see if that introduces the problem.

Unfortunately, I can't reproduce on chromium for Ubuntu, or anything else.

**Comment by ansuz** [comment] 2017-04-03 13:58
The update just finished, and I can confirm that this problem seems to have been introduced in v57.

Now that I can reproduce the problem, it should be easy to fix. Expect the issue to go away when we next release: April 11th.

Thanks for the report!

**Comment by doegox** [comment] 2017-04-03 22:04
Great, thanks for your fast action!
Sorry I should have specified my browser version.
FTR it's Chromium Version 57.0.2987.98 on Debian 9.0 (64-bit)

**Comment by ansuz** [comment] 2017-04-05 10:37
this is now fixed in our staging branch as of this morning.

**Closed by ansuz** 2017-04-05 10:37 UTC
