### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by MomentumFollowUp** [xwiki-labs/cryptpad#614] opened 2020-09-16 08:46 UTC
Frustrated that I could save my Sheet on .pdf. There is no Save button; neither did Ctrl S work or Ctrl P work. Please advise.

**Comment by sisco0** [comment] 2020-09-23 21:26
Have a good day, did you try pressing Ctrl + A, Ctrl + C and Ctrl + V at _Excel_?

**Comment by MomentumFollowUp** [comment] 2020-09-24 23:44
Your instructions was not Valid and Did NOT work  to save the Worksheet.
Could you please INCLUDE 'PRINT' with the File tab in the Spreadsheet?

[image: 2020-09-24_16-41-44.png]
*Bernadette Ferrer *

*LinkedIn <https://www.linkedin.com/in/momentumfollowup/>  *

*"Life is a Sacred Journey. It is about Change, Growth, Discovery, Movement
and Transformation. It is continuously expanding your vision of what is
possible, stretching one's soul, teaching one to see clearly and deeply,
helping one to listen to one's intuition." *
*                                               ---Mother Janet Erskine
Stuart---*

**Comment by sisco0** [comment] 2020-09-25 13:20
Have a good day, please use _Export_ functionality of _CryptPad_ as intended for this purpose.
I uploaded a video for you in order to achieve the functionality that you want using _Microsoft Excel_ (you could use any app that accepts `.xlsx`).
[https://youtu.be/1FcdlT-c4Y4](https://youtu.be/1FcdlT-c4Y4)

Pretty printing when using _CryptPad_ OnlyOffice based sheets is not recommended from any browser.

**Comment by ansuz** [comment] 2020-09-25 14:06
Export to XLSX from CryptPad is supported in Chrome browser, with support for Firefox coming soon.

You can open the exported file in another editor like LibreOffice and print to pdf from there. We'll most likely build in native support for this in the future, but it's not in our immediate roadmap.

Since we already have a number of open issues about export to PDF and other file formats I'm going to close this as a duplicate.

**Closed by ansuz** 2020-09-25 14:06 UTC
Labels: duplicate

**Comment by MomentumFollowUp** [comment] 2020-09-25 19:35
Thank you. I plan to use Cryptpad as an alternative to Microsoft for my
business needs.

Keep me updated on your progress.

Gratefully,

*Bernadette Ferrer *

*LinkedIn <https://www.linkedin.com/in/momentumfollowup/>  *

*"Life is a Sacred Journey. It is about Change, Growth, Discovery, Movement
and Transformation. It is continuously expanding your vision of what is
possible, stretching one's soul, teaching one to see clearly and deeply,
helping one to listen to one's intuition." *
*                                               ---Mother Janet Erskine
Stuart---*
