### ISSUE TITLE
Uploading text file failure

### ISSUE THREAD

**Issue by applecargo** [xwiki-labs/cryptpad#864] opened 2022-02-09 20:15 UTC
**Describe the bug**
Uploading text/plain files doesn't work.

**Where did it happen?**
https://pad.dianaband.info
my own Yunohost instance

**To Reproduce**
1. Go to CryptDrive
2. Click on '+new'
3. Select a text file 'dot_emacs' (a LISP code, without extension)
4. No popup & No response
5. Open Inspector & See error

**Expected behavior**
Upload works.

**Screenshots**
at Firefox
![Screen Shot 2022-02-10 at 4 51 18 AM](https://user-images.githubusercontent.com/3090243/153280012-7f14d864-7e6b-4e93-afa8-be6f642726e8.png)
at Google Chrome
![Screen Shot 2022-02-10 at 4 51 46 AM](https://user-images.githubusercontent.com/3090243/153280145-1ec2153a-6972-4adb-a09e-198371fb19fe.png)

**Browser (please complete the following information):**
 - OS: MacOS Mojave (10.14.6)
 - Browser & Version: Firefox version 96.0.3 & Google Chrome version 98.0.4758.80 (Official Build) (x86_64)
 - Extensions installed
 
[firefox]

Auto Tab Discard
Blank New Tab
BlockTube
Copy as Markdown
Dark New Tab
Dark Reader
Don't track me Google
DownThemAll!
KeePassXC-Browser
OneTab
Tab Center Reborn
uBlacklist
uBlock Origin
Video DownloadHelper
[Disabled] Dark Mode
[Disabled] Tree Style Tab

[google chrome]

Dark New Tab
Dark Reader
Dark Reader Dark
Empty New Tab Page
Google Docs Offline
OneTab
Session Buddy
Stop Autoplay for Youtube
tachyons-x-ray
uBlock Origin
Video DownloadHelper
(Chrome Apps)
Docs
Sheets
Slides
Web Server for Chrome

 - Browser tweaks
 
[firefox] Enhanced Tracking Protection -> Strict

**Additional context**

I am using version 4.11.0.
I have installed it through Yunohost -> https://github.com/YunoHost-Apps/cryptpad_ynh
When I injected a console.log(content), I get an ArrayBuffer not a Blob (of File).
So, I was able to quick-fix it by myself
![Screen Shot 2022-02-10 at 5 08 57 AM](https://user-images.githubusercontent.com/3090243/153281945-5eeac5f9-f11b-47a8-bd17-7eecb331ab75.png)
Maybe I could make a PR but I am not using the same code as you have here. So I leave here a comment.
Plus, I don't know why it was not a Blob at first place !

**Comment by applecargo** [comment] 2022-02-09 20:21
Now, my browsers automatically updated to the latest :

firefox: 97.0
chrome : Version 98.0.4758.80 (Official Build) (x86_64)

and the problem persists.

**Comment by mthld** [comment] 2022-08-02 14:22
Hello,

I cannot reproduce this on v5.0 & sadly we cannot support CryptPad distributions. I invite you to take this issue to https://github.com/YunoHost-Apps/cryptpad_ynh. I'll be closing this issue now. :)

**Closed by mthld** 2022-08-02 14:22 UTC
