### ISSUE TITLE
[Bug] Code pad: Editor area keeps resetting/jumping to recent edits while more than 1 person is editing

### ISSUE THREAD

**Issue by CryptGoat** [xwiki-labs/cryptpad#746] opened 2021-06-07 15:58 UTC
**Describe the bug**
Okay, trying my best to explain this: We mostly organize our collaborative efforts via the code pad editor of CryptPad. A major annoyance is the fact that the editor part of the code pads keeps jumping around / changing the vertical position / the line in focus whenever somebody else is editing the text. This makes simultaneous edits extremely hard. Sometimes putting your cursor as an "anchor" into the line you want to view/edit appears to help sometimes but it doesn't seem consistent. Comparable pad software such as HedgeDoc and Etherpad (Lite) don't have this problem.

**Where did it happen?**
Tested CryptPad.fr and private instance at version 4.6.0.

**To Reproduce**
1. Open any code pad and have multiple people edit it at different points of the text at the same time (text length should be as long as needed to make the editor view scrollable).
2. The editor view should jump to recently edited points/lines of the text.

**Expected behavior**
The vertical position of the editor should just stay where the user has chosen it to be.

**Screenshots**
-

**Browser (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Firefox 89 and Chromium 91, default settings

**Comment by ansuz** [comment] 2021-06-08 13:33
Closing as a duplicate of #731 .

**Closed by ansuz** 2021-06-08 13:33 UTC
Labels: duplicate
