### ISSUE TITLE
Can't create a shared folder

### ISSUE THREAD

**Issue by Genie23** [xwiki-labs/cryptpad#524] opened 2020-04-08 19:22 UTC
Hello I'm a French user of Cryptpad

**Describe the bug**
When I want to create a shared folder, a window appears asking me the name of the folder. I fill it in, I press OK, and nothing happens, the file is not created. I also checked the NodeJS server logs, I have no errors (I use PM2 to manage the NodeJS server) :
```
0|papyrus  | FRESH MODE ENABLED
0|papyrus  | Cryptpad is customizable, see customize.dist/readme.md for details
0|papyrus  | [2020-04-08T18:25:50.598Z] server available http://127.0.0.1:3000
```

**Where did it happen?**
I am using the self hosted version that I installed on my server. The adress is : https://papyrus.genie23.fr

**To Reproduce**
1. Once connected, I click on New pad
2. Then I click on shared folder
3. I enter the name of the folder
4. I press OK
5. Nothing is happening

**Browser (please complete the following information):**
 - OS : Windows 10
 - Browser : Firefox
 - Version : 75.0 (64 bits)
 - Extensions installed :
   - uBlock Origin
   - Kaspersky Protection
   - Kaspersky Password Manager
 - Browser tweaks :
   - Enhanced Tracking Protection : custom
   - Don't track me : always

**Comment by ansuz** [comment] 2020-04-08 20:15
I don't know if this is the cause of this particular problem, but your instance is not correctly configured. The [/api/config](https://papyrus.genie23.fr/api/config) endpoint returns `"httpUnsafeOrigin": "http://localhost:3000/",`. Please see the comment [in the example config](https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js#L38-L49).

**Comment by Genie23** [comment] 2020-04-08 20:30
I replaced the address "http://localhost:3000/" by 'https://papyrus.genie23.fr/', then I restarted my PM2 instance, but it didn't change anything.

**Comment by Genie23** [comment] 2020-04-09 12:16
I had to go back in the configuration of the cryptopad server. Indeed, with `"httpUnsafeOrigin": "http://papyrus.genie23.fr/"`, I could no longer open any document.

**Comment by ansuz** [comment] 2020-06-03 19:14
I'm closing this as it seems like a configuration issue, not a bug in the software.

**Closed by ansuz** 2020-06-03 19:14 UTC
Labels: configuration
