### ISSUE TITLE
Feature request: Add ability to share documents with not registered users

### ISSUE THREAD

**Issue by vasilevich** [xwiki-labs/cryptpad#461] opened 2019-11-02 13:38 UTC
Hi, I am not 100% sure but I think its a bug, or intended,  since version 3.3 :

when I create a new cryptpad, I can share it with registered users but there is no way to share it with non registered users, which renders the embed feature useless,  since I can't now embed it in my websites expecting every single user to register to the cryptpad service is unrealistic and impractical.

Now if i want to share for example a spreadsheet to be editable with my friends, who do not want to create an account, they dont even know what cryptpad is.  
I have to logout of my user, and then create the pad.  then it will be shared OK with any unregistered user.

Please give some ability to share pads with non registered users as a registered user.
I think this is a major and very critical feature of your app.  embedding pads in website is a very nice way of using this nice technology but this might stand in the way.

Thanks!

![image](https://user-images.githubusercontent.com/1217224/68071840-6ba68c00-fd87-11e9-9fb3-c3a66c90d1eb.png)

**Comment by yflory** [comment] 2019-11-04 12:37
Hi,
Unfortunately, spreadsheets can't be shared with unregistered users for now. This is a technical restriction and not something we really want. We'll try to enable at least the "view" access for unregistered users in the near future.
You should be able to share any other type of pad (rich text, code, slide, etc.) with unregistered users.

**Comment by vasilevich** [comment] 2019-11-04 14:53
Hi, thank you for explaining the issue.

can you link to, or go into a bit more detail for the reason why is this a technical restriction,
so that potential developers such as me ,who would like to contribute, would take a look and try to help you fix it.

Thanks

**Comment by ansuz** [comment] 2020-01-03 22:24
I'm closing this issue as a duplicate of #390

**Closed by ansuz** 2020-01-03 22:24 UTC
Labels: spreadsheets
