### ISSUE TITLE
calendar: all day entries misplaced in mobile browser only

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#715] opened 2021-04-15 22:51 UTC
**Describe the bug**
A event that spans several days shows up on mobile browsers (tested on latest chrome mobile) out of place. See screenshots 
![image](https://user-images.githubusercontent.com/119662/114947638-c5045d00-9e4d-11eb-913d-a0ad888f0cd1.png)
![signal-2021-04-16-004639](https://user-images.githubusercontent.com/119662/114947669-d8172d00-9e4d-11eb-8488-0be51d13f19f.png)

**Comment by ansuz** [comment] 2021-04-16 08:21
Thanks for the report!

Calendars won't be stable until at least next release, but we'll keep this in mind for later.

**Comment by cyphunk** [comment] 2021-04-17 11:11
A ok. For future reference I see that the all day events show up on current day always. Meaning today they show up I 17th and tomorrow they will show up on 18th and so forth

**Comment by ansuz** [comment] 2021-05-06 08:40
Our [latest release](https://github.com/xwiki-labs/cryptpad/releases/tag/4.5.0) includes a lot of fixes for mobile styles on the calendar app, so I flagged this as `fixed in staging` yesterday when I couldn't reproduce the issue. Unfortunately my colleagues informed me that they were never able to reproduce to begin with either. 

It's possible this only occurs on a particular device or browser. As such we'll need you to confirm whether the issue still occurs in the original context and if so what device and browser you're using.

**Comment by ansuz** [comment] 2021-07-07 11:31
> A event that spans several days shows up on mobile browsers (tested on latest chrome mobile) out of place. See screenshots
image

We received another report of this affecting browsers on iOS and included a fix in today's release. 

For future reference, please note that Apple requires third-party browser vendors to use the system's layout and javascript engines in their browsers. As a result, bugs that may appear to affect Firefox, Chrome, and any other browser on iPhones often stem from Apple's policies which intentionally deliver a sub-par experience for the web (vs apps on the app store). When reporting bugs that affect iPhone it's critical to report the OS rather than the apparent browser vendor.

**Closed by ansuz** 2021-07-07 11:31 UTC
Labels: beta, fixed in staging, mobile support
