### ISSUE TITLE
http://[::]:3000/drive/ is not loading

### ISSUE THREAD

**Issue by Z33DD** [xwiki-labs/cryptpad#382] opened 2019-05-29 01:42 UTC
I'm followed the update guide but after the upgrade I'm can't use Cryptpad, the main screen after login isn't loading. I'm not sure, but if I copy the datastorage/ folder, install Cryptpad from scratch again and copy my old datastorage/ to the folder of new installation can solve the problem.

**Comment by ansuz** [comment] 2019-06-03 16:02
Are there any errors printed in the browser's console?

**Comment by Z33DD** [comment] 2019-06-04 18:11
No, It's seems like work, but the UI in the browser don't works

**Comment by Zalaxx** [comment] 2019-06-29 06:50
I have the same issue, and some error on my console. It looks like it came from the CSP header. Here's a screen of the errors. I can give other information if necessary, just tell me which.
![Screenshot from 2019-06-29 08-44-14](https://user-images.githubusercontent.com/35188982/60380716-93808e80-9a39-11e9-8954-2bb595541924.png)

**Comment by cremesk** [comment] 2019-07-02 07:56
I think i have the same Issue here.
[https://pad.envs.net/](https://pad.envs.net/)
The Page hangs on - initial the Pad ..

**Comment by yflory** [comment] 2019-07-02 08:43
@cremesk I just reproduced the issue on your instance and it seems there is a problem with the websocket connection:

> Firefox can’t establish a connection to the server at wss://pad.envs.net/cryptpad_websocket.

I'm going to try to reproduce with a fresh install on a debian machine, but it may also be an nginx config issue.

**Comment by cremesk** [comment] 2019-07-02 09:04
@yflory okay.. i think its possible. My nginx config file: https://0x0.envs.net/P.conf
In the config.js i havee change the Line 18 to:
`var domain = 'pad.envs.net https://pad.envs.net ' + _domain;`

**Comment by cremesk** [comment] 2019-07-04 15:38
Everyone have a Idea for me to fix the Problem? Thanks

**Comment by cremesk** [comment] 2019-07-17 15:02
@yflory hey, you have any news for me please?

**Comment by ansuz** [comment] 2019-07-17 15:17
I just tried connecting to the websocket directly via nodejs using [this package](https://www.npmjs.com/package/netflux-websocket) which implements the websocket protocol we use between the server and clients. Since it's not in a browser context this eliminates a lot of factors as potential causes.

I received this error:

```
Error: unexpected server response (200)
    at ClientRequest._req.on (/home/ansuz/code/web/xwiki/is-cryptpad-api-up/node_modules/ws/lib/WebSocket.js:653:21)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
```

For whatever reason it looks like the websocket traffic is getting mangled and I imagine nginx is responsible. You could test this by allowing clients to connect directly to the nodejs process over http on port 3000. If it works, then it's not an issue with the CryptPad server, but the reverse proxy or its configuration.

**Comment by cremesk** [comment] 2019-07-20 10:20
I have test it again.. same problem.

i have enable the debug mode with silly option in the config.js.
I become only this output:
```
$ node server
[2019-07-20T10:14:38.522Z] server available http://[::]:3003
Cryptpad is customizable, see customize.dist/readme.md for details
[SILLY] 2019-07-20T10:14:38.531Z LOADING RPC MODULE undefined
[SILLY] 2019-07-20T10:14:38.544Z HK_LOADING LOADING HISTORY_KEEPER MODULE
[VERBOSE] 2019-07-20T10:14:38.544Z HK_ID History keeper ID: fe2bd9795b40ca5d
```

when i connect to 'pad.envs.net/cryptpad_websocket' or localhost:3000 i become with 'lynx'
this output:
```
OOPS In order to do encryption in your browser, Javascript is really really required.                                                                                                                                                       
                                                                                                                                                                                                                                               
   OUPS Afin de pouvoir réaliser le chiffrement dans votre navigateur, Javascript est vraiment nécessaire.
```

**Comment by cremesk** [comment] 2019-07-21 13:37
and a test with apache2 with the same issue :/

**Comment by ansuz** [comment] 2019-07-22 08:38
> [2019-07-20T10:14:38.522Z] server available http://[::]:3003

Your websocket server is listening on port 3003 

>  proxy_pass http://localhost:3000;

and your reverse proxy is forwarding to port 3000.

Your clients can't connect to the websocket server because you're forwarding to a port with nothing listening.

> when i connect to 'pad.envs.net/cryptpad_websocket' or localhost:3000 i become with 'lynx'

This is expected behaviour. Lynx will never be able to run CryptPad.

**Comment by cremesk** [comment] 2019-07-22 08:56
Sorry it only a copy & past failure.
I have test the setup with port 3003. But i have the same problem and then i change back to 3000. (config.js and reverse proxy config) ;)

I have not an javascript browser on my server..
how can i debug the ws connectection?
where are the logs?

apache2 conf: https://tb.envs.net/8sg6
config.js: https://tb.envs.net/otpx/

Thanks for help

**Comment by ansuz** [comment] 2019-07-22 09:16
I meant to suggest not that you try to access it locally from the server but that you unblock access to port 3000 from outside the server. That would mean dropping your firewall on that port.

You can replace all of the CSP rules in your config.js with empty arrays and connect directly to the nodejs process. You'll need to disable CSP because (I assume) it's currently set up for your public domain. If it works, then the issue is with the reverse proxy configuration and not the nodejs process.

If you join our [Matrix channel](https://riot.im/app/#/room/#cryptpad:matrix.org) you should find lots of other admins who have set up their own instances with various configurations, so they can likely offer tips for different configurations.

**Comment by cremesk** [comment] 2019-07-22 09:49
i have open port 3000 and comment the csp part in the config.
```
192.168.1.1 - - [22/Jul/2019:09:44:52 +0000] "GET /api/config?cb=16c1911cb4c HTTP/1.0" 200 508 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:44:52 +0000] "GET /common/common-realtime.js?ver=2.25.0 HTTP/1.0" 200 579 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:44:53 +0000] "GET /pad/ HTTP/1.0" 200 537 "https://pad.envs.net/pad/" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:44:53 +0000] "GET /api/config?cb=16c1911d060 HTTP/1.0" 200 508 "https://pad.envs.net/common/outer/sharedworker.js?ver=2.25.0" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:44:56 +0000] "GET /cryptpad_websocket HTTP/1.0" 200 1019 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:45:03 +0000] "GET /cryptpad_websocket HTTP/1.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:45:03 +0000] "GET /api/config?cb=16c1911f838 HTTP/1.0" 200 508 "https://pad.envs.net/cryptpad_websocket" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:45:04 +0000] "GET /customize/pages/cryptpad-websocket.js?ver=2.25.0 HTTP/1.0" 404 805 "https://pad.envs.net/cryptpad_websocket" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:45:04 +0000] "GET /customize/src/less2/pages/page-cryptpad-websocket.less?ver=2.25.0 HTTP/1.0" 404 805 "https://pad.envs.net/cryptpad_websocket" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.1 - - [22/Jul/2019:09:45:28 +0000] "GET /cryptpad_websocket HTTP/1.0" 200 1019 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
```

i cant find this page:
`/customize/src/less2/pages/page-cryptpad-websocket.less`

**Comment by cremesk** [comment] 2019-08-01 18:06
i have found a solution.
i need only a simple add of this lines on my hostservers nginx proxy:

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";

nginx host config: https://0x0.envs.net/x.conf
nginx lxc config: https://0x0.envs.net/-.conf

best regards,
~creme

**Comment by vigneshtdev** [comment] 2019-08-29 16:43
replacing _domain value in `config.js` to http://127.0.0.1:3000/ seems solve  CSP issue for me

for local development

**Comment by ansuz** [comment] 2019-12-05 17:23
Closing this as it seems like a configuration error.

For the record we have a project proposal awaiting confirmation which will include improving documentation for admins.

**Closed by ansuz** 2019-12-05 17:23 UTC
Labels: More info needed, configuration

**Comment by Guiraud** [comment] 2020-08-28 19:58
This [comment](https://stackoverflow.com/questions/23931987/apache-proxy-no-protocol-handler-was-valid#comment50686096_26045183) helped me, despite the script that you gave.
```BASH
sudo a2enmod proxy_wstunnel
```
In addition of : 

```BASH
sudo a2enmod ssl
sudo a2enmod proxy
sudo a2enmod proxy_balancer
sudo a2enmod proxy_http
```
