### ISSUE TITLE
RichText pad duplicates text by itself

### ISSUE THREAD

**Issue by kallekruse** [xwiki-labs/cryptpad#352] opened 2019-04-02 08:14 UTC
We are having trouble using cryptpad for collaboratively editing a RichText document: From time to time a seemingly random section of a line gets duplicated a number (10 or 20 or even more) of times, like a copy&paste running wild. So...
`This an example`
...might become...
`This an examplen examplen examplen examplen examplen example`
...without anybody of us having intentionally edited that line.

Usage pattern: a pad hosted on cryptpad.fr, accessed by a handful of people, sometimes in parallel, on Android and Ubports mobile devices as well as Ubuntu desktops.

Unfortunately we do not know how to reproduce the observed behaviour. It happens from time to time, sometimes multiple times a week, with months of correct behaviour in between. 

Another user group told me that they observe the same issue, with a similar usage pattern (no Ubports device involved there).

**Comment by ansuz** [comment] 2019-04-03 15:44
We've gotten a few reports about this, but we haven't been able to reproduce it.

If you have a link to document where this occurred and you don't mind sharing it with us, it might help us to figure out the cause.

You can mail it to contact@cryptpad.fr.

**Comment by kallekruse** [comment] 2019-04-13 19:29
Thanks for the response, @ansuz ! Unfortunately our pad contains sensible data, so no. Also I wonder if in general it is good advice to share cryptpad links by unencrypted email (you did not point me to a GPG key so i assume this was your suggestion)?

We will try to provoke the bug on a toy pad and if successful I will provide you with the link.

**Comment by kallekruse** [comment] 2019-06-02 19:48
For the records: The bug is still occuring from time to time.

**Comment by ansuz** [comment] 2019-06-03 14:15
We believe we've figured out the root cause of this problem, but unfortunately it's related to some code deep in the heart of CryptPad which would affect most of the platform if we got it wrong. Pads, user accounts, and a variety of features are all built on one type of data structure, so changing how it works is scary.

From what we can tell this behaviour is triggered when a member of a session has a very asymmetric connection to the server (good upload speed and bad download speed). They send patches, but never receive acknowledgement that the patch was received by the server, so they send again. Other clients don't distinguish between multiple messages with the same content, so they insert the same content multiple times.

We're discussing various means of fixing this, but I can't promise a particular date for when it will be fixed.

**Comment by mal0ki** [comment] 2019-06-11 17:38
This is one of the bugs I came here to report. 

It'll take half a sentence usually while 2 people are editing the document at the same time, and keep copying endlessly until all parties leave the document.

**Comment by adzialocha** [comment] 2019-07-02 18:06
We observed that behaviour after someone reverses a change via *Undo*, hope this helps somehow.

**Comment by lkiesow** [comment] 2019-07-10 20:36
We did some tests with CryptPad in different scenarios and unfortunately, this bug showed up in all of them. Sometimes less often (once in a larger document), sometimes it basically breaks the whole document. We once tried in a meeting with ~20 people over wifi. That ended up in a weird document which took some time afterward to reconstruct manually. This was, what caused us to stop putting CryptPad into production use for the moment. So it would be great if this could be fixed.

**Comment by tuxayo** [comment] 2019-07-23 09:11
Maybe related: I have a document that almost inevitably leads to this bug. One of the client will duplicate indefinitely a part of the text. A part which wasn't even touched.

When opening the document, I get these JS errors:
```

uncaught exception: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data boot2.js:46:9
    onerror https://cryptpad.fr/common/boot2.js?ver=2.25.0-5:46

SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data sframe-app-outer.js:29:29
    onMsg https://cryptpad.fr/common/sframe-app-outer.js?ver=2.25.0-5:29

```

Copying the content to a new rich text document doesn't lead to the same JS errors.
HTML export and import also. Does anyone know a way to fully copy a document?

**Comment by tuxayo** [comment] 2019-07-23 09:28
maybe related: #388

**Comment by whale1432** [comment] 2019-07-31 17:41
We are experiencing the same bug. Additionally it is almost impossible to edit a shared document on a mobile device as the cursor is jumping randomly through the text no matter where you place it. Sometimes yo start typing a sentence and in the middle of typing the cursor jumps to another position in the text. These two bugs make it absolutely impossible to work with cryptpad in a team. Please fix this bug soon, otherwise we‘ll have to use another platform.

**Comment by jamieforth** [comment] 2020-01-28 16:53
We experienced the same behaviour today with six people editing the same pad. Cryptpad 3.8 (89d9f22e) behind nginx.

Not sure if it was related but it occurred at the same time a couple of us were trying to highlight different parts of the document simultaneously.

**Comment by ansuz** [comment] 2020-02-25 15:44
We believe that we've fixed this issue, but time and further testing will tell. The proposed fixes have been merged to master and deployed to CryptPad.fr as a part of our [v3.12.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.12.0).

**Comment by kallekruse** [comment] 2020-02-28 08:50
Sadly the bug appeared again yesterday (2020-02-27) on a CryptPad.fr pad.

**Comment by kallekruse** [comment] 2020-03-05 19:14
Can this be reopened, @ansuz ? The bug is not fixed.

**Comment by schoolsupplies** [comment] 2020-03-23 03:01
Hi all, wanted to report that the bug appeared for me today (3/22). Multiple people signed on to a pad and actually it was okay after we left the pad. When I came to check a few hours later, the duplicates happened.

**Comment by virtualcharlotte** [comment] 2020-03-29 15:06
We've experienced the bug fairly recently (27/3). The doc had been shared to around 40 people, likely 3-4 editing at the same time tops

**Comment by GerJuli** [comment] 2020-03-29 15:09
Appears on multiple instances I host too. starting with ~8-12 People working on one document. All instances are on the newest version.

**Comment by Jegmi** [comment] 2020-03-30 09:48
Same bug 29/3. We were 8-16 people in a variety of rich-text documents, so there were a lot of "lurking coursers" everywhere, and these coursers kept "spitting out" their last edits, sometimes 100s of time. As much as I love the cryptpad, this bug makes it close to unusable for real time collaboration. This is why I would strongly recommend to make it one of your highest priorities to fix it. Thank you so much for your effort and (otherwise) really amazing product!

**Comment by davidbenque** [comment] 2020-03-30 10:29
Thank you for reporting on this. We are now treating this with the highest priority. On cryptpad.fr we are disabling the ability to see other people's cursors to prevent this from happening until we fix the bug (you have to reload the page for this take effect).

**Comment by davidbenque** [comment] 2020-03-30 12:10
If anyone is willing to share a pad where this bug happens and no confidential data are stored it would help us as we try (but fail so far) to reproduce it. You can use the support ticket functionality within CryptPad to share it securely with us.

**Comment by Jegmi** [comment] 2020-03-30 12:14
Hi! 

Here is a link to a pad. At the top you see that "(back to main)” has a small self-copy:

https://cryptpad.fr/pad/#/2/pad/edit/Xxsq+FiAmsBpu20cpapf3WOk/ <https://cryptpad.fr/pad/#/2/pad/edit/Xxsq+FiAmsBpu20cpapf3WOk/>

Here are some screenshots of previous problems:


Does that help? 

Thank you for working on it!! It’s much appreciated!
Jannes

**Comment by yflory** [comment] 2020-03-30 14:58
Thank you for the link, it was very useful to find the cause of the issue. We believe we've finally fixed it!

The fix has been deployed on cryptpad.fr, unfortunately the problem can still happen until everybody in the pad has reloaded the page.

**Comment by Jegmi** [comment] 2020-03-30 15:09
Great! Thank you for your amazingly quick response! I’m looking forward to testing in the next collaborative session. And I’ll make sure we donate to your project.

Best
Jannes

**Comment by MacLemon** [comment] 2020-03-31 10:40
The technical university Vienna is using our pads quite frequently and they seem to have come up with a way to reproduce that “text duplication” problem. \o/

Here's their [pads.c3w.at debugging](https://cryptpad.fr/pad/#/2/pad/edit/4bRFJacp2mHweQkHq0JMvmJT/) write up on the issue. It's in german and I only post it here for completeness. This is what is says:

## Steps to reproduce
1. Create a new Rich-Text pad
2. Add some text to that pad
3. Add a link to the pad, then add more text
4. Click that link
5. Click the popup to actually follow the clickable link in that popup.
(This leaves the cursor within that link)
6. Keep the document open, but in the background for “some time”.
7. Once you return to the Pad some text seems to multiply. It *seems* to be the text to the right of the caret.

They suspect that this is more likely to happen when there are links in the pad and your cursor is within that link after clicking it. (Which opens a new tab/window)
They are able to reproduce this on [pads.c3w.at](https://pads.c3w.at) and [cryptpad.fr](https://cryptpad.fr).


I've requested more info on what the vague “return after some time” means in more SI-Unit like measurements and which browsers they mostly use. Once I get those, I'll add that info here.

**Comment by MacLemon** [comment] 2020-04-11 21:37
Sad having to tell you this, but the issue still persists in 3.15.0.
I kept a tab open in Firefox 76.0 (Developer Edition)  with a [Testing /pad](https://cryptpad.fr/pad/#/2/pad/edit/4bRFJacp2mHweQkHq0JMvmJT/) and it did duplicate text by leaving the cursor within a link. (Like it happens when you click a link and continue surfing in that other window/tab.)
Behaviour is the same on cryptpad.fr and pads.c3w.at.

It *seems* to be slower in multiplying text though.

**Comment by ansuz** [comment] 2020-04-14 19:39
Thanks for the update!

**Comment by MacLemon** [comment] 2020-04-17 10:34
There's another pad which, according to that Uni Professor who uses our instance with their students, duplicated about 64k of text.
You can see that in the pad's history.
https://pads.c3w.at/pad/#/2/pad/edit/OOu0ZmIF+FOm11asIxHJU7Yg/

Again, this is a Rich-Text pad which, so far, seem the only ones affected by that problem.

To me it seems best reproducible with the “cursor in a link” method as outlined above.

**Comment by ansuz** [comment] 2020-04-21 21:14
Thanks for the report! It's encouraging that it only seems to occur in one case.

**Comment by ansuz** [comment] 2020-06-19 17:18
Has this issue occurred recently? We've stopped receiving reports via our support tickets.

**Comment by wolfskaempf** [comment] 2020-06-19 17:35
Do we know what caused it and how it was fixed? Would be very curious to know more about this!

To answer your question: I have not experienced this behaviour in the past few weeks.

**Comment by MacLemon** [comment] 2020-06-23 14:26
From my quick tests with CryptPad v3.19.0 (Thylacine) on our instance, I was not able to reproduce the problem anymore.
But unless we know what the cause of the problem was, how can we be sure?

**Comment by ansuz** [comment] 2020-06-23 15:28
We can always re-open the issue :wink:

**Closed by ansuz** 2020-06-23 15:28 UTC
Labels: bug

**Comment by VirtuOes** [comment] 2023-03-07 13:12
Hi, we are using the XWiki Debian 13.10.10 Version. 
User Setup is Google Chrome under Windows.

Our users report the above mentioned bugs. 
Are there addtional users having the problem again?

**Comment by mflorea** [comment] 2023-03-08 08:18
@VirtuOes XWiki and Cryptpad  are two separate projects. If you're having issues with the real-time editor in XWiki then you should report it at https://jira.xwiki.org/issues/?jql=project%20%3D%20XWIKI%20AND%20component%20%3D%20Realtime . You can also ask questions on https://forum.xwiki.org/ if you're not sure about the behaviour you're noticing.
