### ISSUE TITLE
Not able to edit pads collaboratively anymore

### ISSUE THREAD

**Issue by laurinhansen** [xwiki-labs/cryptpad#396] opened 2019-06-26 20:41 UTC
Hello,

not too long ago I set up a shared folder pad for multiple users to collaborate on multiple pads. Since yesterday, only I, the owner of the shared folder, can access all the pads and folders in the shared folder. Everyone else can either, when not logged in, see every pad and folder, but neither access nor edit, or, when logged in, see only the sub-folders but neither edit nor click on anything. Is this a known issue and does anyone know how to fix it? Thanks for any help.

**Comment by ansuz** [comment] 2019-06-27 08:38
Hi,
If they can see the structure of the folders then they should have access to all the keys necessary to access the pads, so this sounds like an error in the UI.

I have a few questions:

1. Are you experiencing this issue on CryptPad.fr or a different instance?
2. What browsers are you and the other editors using?
3. Are there any red messages printed in the console? If you haven't had to look in the browser's console before, there's a brief guide on doing so [here](https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors).

Once we have some more info we should be able to fix the problem.

**Comment by laurinhansen** [comment] 2019-06-27 09:50
Hi, thank you for your response.

1. We are experiencing the issue on CryptPad.fr
2. We are using Tor Browser.
3. In my console it only says in red:
"Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively." when I open one of the pads. This is in my own browser console with the pads working just fine.

One of the collaborator who can't open sub-folders or pads, these are the red messages appearing when opening the main folder (accessible, but only the sub-folders are visible, and they can't be accessed):
"Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames. (unbekannt)" [this is the same message I get, only in German]
"Die Ressource von "https://cryptpad.fr/drive/" wurde wegen eines MIME-Typ-Konfliktes blockiert (X-Content-Type-Options: nosniff).[Weitere Informationen]  (unbekannt)" [engl.: the ressource from [...] was blocked because of a MIME-type-conflict.]

Upon trying to open one of the sub-folders:
"Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames. (unbekannt)" (same as above)
"An error occurred executing the cmd_copy command: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIController.doCommand]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://global/content/globalOverlay.js :: goDoCommand :: line 84"  data: no]"


Thanks for your help!

**Comment by ansuz** [comment] 2019-06-27 10:05
> We are using Tor Browser.

Which version and which security mode are you using? It could be that some functionality we depend on is being blocked.

**Comment by ansuz** [comment] 2019-06-27 10:11
I'm testing with Tor browser 8.5.3 on standard mode and unfortunately I can't reproduce your error.

**Comment by laurinhansen** [comment] 2019-06-27 11:39
> I'm testing with Tor browser 8.5.3 on standard mode and unfortunately I can't reproduce your error.

This is the version we're using as well.

**Comment by ansuz** [comment] 2019-06-27 11:45
and the security modes?

**Comment by laurinhansen** [comment] 2019-06-27 13:04
> and the security modes?

is set on Standard mode

**Comment by ansuz** [comment] 2019-06-27 13:08
Is your tor browser customized beyond the basic add-ons that come with it?

I tested with the same settings and didn't get any error.

If any of your peers are willing to try opening their account and shared folders in a browser other than tor, that would tell us whether it's an issue with the account or specifically their browser setup.

**Comment by laurinhansen** [comment] 2019-06-27 20:52
No, none of us have any add-ons or customizations. We've tried re-installing of Tor and logging into the the owner-account from another computer, which didn't help. Logging in from Firefox didn't help either.

**Comment by ansuz** [comment] 2021-05-06 08:07
It's been a long time since this issue was last updated, so I'm going to close it. Please comment if the issue is still occurring.

**Closed by ansuz** 2021-05-06 08:07 UTC
