### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by Avasz** [xwiki-labs/cryptpad#99] opened 2017-03-16 12:54 UTC
Hi, Thanks for this awesome app. I tried the demo version and was very much impressed, so wanted to self-host it.
I followed all the steps mentioned in the readme. 
I can browse to the homepage using http://localhost:3000, but after that if I try to create any pads, it gets stuck at the loading screen. Everything is configured as default.

Also, cannot create a user account. It gives 'Hashing your password" and after that "An unexpected error occurred"

I tried in different systems:
Centos 7 with node 6.9.4
Debian Stretch with node 6.9.5
And Debian Jessie.

Please help if I missed some steps or did something wrong.

Thanks

**Comment by ansuz** [comment] 2017-03-16 13:38
I see the issue, and it will be fixed shortly.

The problem is that your server is sending security headers which tell your browser not to trust any server except the one at `cryptpad.fr`. It does that because we accidentally left those headers in `config.js`. You should be able to do one of two things:

1. Comment out any line that has `cryptpad.fr` using a javascript line comment (`//`)
2. modify the offending lines to match whatever domain you are using
  * `localhost:3000` should work for `child-src`
  * `ws://localhost:3000` should work for `connect-src`

Option 2 is safer, but for local testing, option 1 should be sufficient.

If you want to set up CryptPad on a remote server, you'll need to configure these lines, so it's worthwhile to understand how they work.

**Comment by Avasz** [comment] 2017-03-16 14:30
I tried both the methods. Didn't work. Still loading. :(

**Comment by ansuz** [comment] 2017-03-16 14:44
I just pushed some changes to the default config (`config.js.dist`) which I've tested locally.

If you pull from master, and `cp config.js.dist config.js` once more, it should work.

Just be very careful deploying this, as those headers are sent to clients to protect them. We wrote a blog post about the reasoning that led to this configuration. You can read it [here](https://blog.cryptpad.fr/2017/03/06/Security-growing-pains/).

**Comment by Avasz** [comment] 2017-03-16 14:48
Yes this one worked. Thanks a lot!
I will be deploying this in a server accessible only via VPN to use with my friends, so should be good IMO.
Read the blog post. 
If I were to deploy this in publicly accessible server then I guess the 2nd method mentioned in your previous reply should work, right?

**Comment by ansuz** [comment] 2017-03-16 15:26
Yes, that's correct. We like to advocate _layered security_, though.

Having the access control via your VPN definitely provides another barrier to any adversaries, however the CSP headers can't hurt (assuming they are configured correctly).

Thanks for catching this bug, please do let us know if you find any more.

**Closed by ansuz** 2017-03-16 15:26 UTC

**Comment by dalareo** [comment] 2017-04-28 10:10
I think I am getting the same error when trying to create any content after installing:

```
Refused to connect to 'ws://0.0.0.0:3000/cryptpad_websocket' because it violates the following Content Security Policy directive: "connect-src 'self' ws://* wss://*".
```

**Comment by ansuz** [comment] 2017-04-28 10:39
CryptPad's default config _should_ work as-is without modifications. If you've changed it to suit your server config, I'd recommend joining our [matrix/irc channel](https://riot.im/app/#/room/#cryptpad:matrix.org) for more help from the community.

**Comment by dalareo** [comment] 2017-04-28 10:58
But I am cloning the repo "as it is" when getting this error. No customization at all

**Comment by ansuz** [comment] 2017-05-03 11:52
Apparently this a new issue with chrome/chromium version 58. We've reproduced it.

Workarounds are to either use Firefox or change the connect-src line to `"connect-src 'self' ws: wss:",`

**Comment by ansuz** [comment] 2017-05-03 11:55
We're updating our default config to match. The relevant commit can be found [here](https://github.com/xwiki-labs/cryptpad/commit/e280b92bdb8e1c8cc401d9c74b8c64b5faf80b77). This will be merged to master for our upcoming release on May 9th, 2017.

**Comment by dalareo** [comment] 2017-05-03 13:25
Great!!!

**Comment by dalareo** [comment] 2017-05-09 11:09
I am trying with current version (patch applied??) but still getting the same behaviour (stuck at loading with Google Chrome)

**Comment by yflory** [comment] 2017-05-09 12:10
The fix is available in today's release (in the master branch). You have to copy the config example again (or fix your config.js) to fix the issue in Chrome:
`cp config.example.js config.js`
