### ISSUE TITLE
Translations to other languages ?

### ISSUE THREAD

**Issue by JtLively** [xwiki-labs/cryptpad#50] opened 2016-10-14 19:08 UTC
Mandarin and Spanish at least?

**Comment by heticor915** [comment] 2016-10-21 02:57
I will help you with Spanish @JtLively.

**Comment by heticor915** [comment] 2016-10-21 12:24
@JtLively @ochronus What it mean WYSIWYG PAD?.

**Comment by JtLively** [comment] 2016-10-21 14:33
@heticor915 - I don't know any spanish.
"What You See Is What You Get"

**Comment by heticor915** [comment] 2016-10-21 20:55
@cjdelisle  Thanks. I will let this in my messaje.es.js
    out.button_newpad = 'CREAR NUEVA WYSIWYG PAD';

**Comment by heticor915** [comment] 2016-10-21 21:46
spanish translation is solve in #54, but the ci travis robot says it fail because apparently  there is a ; missing.check #54

**Comment by ansuz** [comment] 2016-10-21 21:47
Sorry for not responding sooner. We're working on making things more translatable, but unfortunately we can't say when we'll be done adding new strings to the translations.

In practice, this means that translations are one more thing to maintain, as long as we keep adding new UI elements to the interface. We'd like to stabilize things, but this is new technology and we still don't know what user experience makes the most sense. We're definitely open to suggestions, though!

In the meantime, members of our development team speak English, French, and German. We can't commit to providing full support to anything outside of that, and must rely on PRs to fix anything that's missing.

**Comment by heticor915** [comment] 2016-10-21 21:50
Cool I could help with the spanish part meantime others join to the cause and project.

**Comment by ansuz** [comment] 2016-10-24 10:29
@JtLively you can follow along with @heticor915's PR [here](https://github.com/xwiki-labs/cryptpad/pull/54).

I'll see about putting together documentation for the steps involved in adding a translation as soon as possible. Mandarin would be a welcome addition.

**Comment by ansuz** [comment] 2016-11-04 09:44
@JtLively, the Spanish translation will be deployed soon (probably today). I'm going to work on some documentation regarding the steps necessary to add a translation.

I'll update you when those docs are available.

**Comment by ansuz** [comment] 2016-11-04 13:57
@JtLively, I made a translation guide which can be found [here](https://github.com/xwiki-labs/cryptpad/blob/master/customize.dist/translations/README.md).

**Comment by JtLively** [comment] 2016-11-04 22:00
Awesome. You guys are great! I'll start working on this during downtime and try to get some others involved. I'll also push this to the Linux deepin forums and see if anyone there wants to help.

**Comment by michaelachmann** [comment] 2016-11-19 08:09
I am working on a German translation and will push it soon.

**Comment by ansuz** [comment] 2016-12-19 10:35
Since everything discussed here (except Mandarin) has been merged, I'm going to close this.

**Closed by ansuz** 2016-12-19 10:35 UTC
Labels: enhancement, help wanted
