### ISSUE TITLE
expire-channels.js throws error

### ISSUE THREAD

**Issue by Marx1st** [xwiki-labs/cryptpad#539] opened 2020-04-28 11:30 UTC
As far as I understand I have to run the script "expire-channels.js" regularly to expire channels, but when I run "node scripts/expire-channels.js" I get an error:

`root@cryptpad:/opt/cryptpad# node scripts/expire-channels.js
/opt/cryptpad/lib/storage/tasks.js:362
    if (!config.store) { throw new Error("E_STORE_REQUIRED"); }
                         ^

Error: E_STORE_REQUIRED
    at Object.Tasks.create (/opt/cryptpad/lib/storage/tasks.js:362:32)
    at /opt/cryptpad/scripts/expire-channels.js:26:11
    at waitFor (/opt/cryptpad/node_modules/nthen/index.js:25:30)
    at Timeout._onTimeout (/opt/cryptpad/www/common/common-util.js:43:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

**Where did it happen?**

own installation (CryptPad v3.15.0 (PigFootedBandicoot))

**To Reproduce**

cd to your Cryptpad directory and run: node scripts/expire-channels.js

**Expected behavior**

All pads with an expiration date should get expired

**Additional context**

The documentation does not include any information which scripts should be run (by cron) and what their exact purpose is.

**Comment by francoisjacquet** [comment] 2020-06-24 13:03
Same here, any update?

**Comment by ansuz** [comment] 2020-06-24 14:25
There was a regression in this script when we updated the file storage API to report errors instead of throwing. I just pushed [a patch](https://github.com/xwiki-labs/cryptpad/commit/131b985902d767f1faf29dfb26de9730d42136bf) to our `staging` branch which uses the updated API correctly.

In any case, you only need to run this script manually if you've explicitly disabled automatic task execution via your config.js file with `disableIntegratedTasks: true`, as per [this line](https://github.com/xwiki-labs/cryptpad/blob/staging/lib/historyKeeper.js#L264).

Normally I wait until a patch is merged to close an issue, but since there's really no reason why anyone should need this script I'll just close this now.

**Closed by ansuz** 2020-06-24 14:25 UTC
Labels: bug, fixed in staging
