### ISSUE TITLE
unable to select text (by double tapping or touch and hold) on Android for formatting

### ISSUE THREAD

**Issue by yrv0** [xwiki-labs/cryptpad#733] opened 2021-05-19 07:27 UTC
![Screenshot_2021-05-19-14-42-03-30](https://user-images.githubusercontent.com/84438976/118787414-7153bc00-b8b0-11eb-9adc-bb561a8025ba.jpg)
On double tapping

![Screenshot_2021-05-19-14-41-58-92](https://user-images.githubusercontent.com/84438976/118787459-7add2400-b8b0-11eb-9666-10819731a239.jpg)
On Touch and hold

**Describe the bug**
unable to select text (by double tapping pr touch & hold) on Android for formatting. The selection (by double tapping or touch & hold) works sometimes, but most of the time it doesn't, currently i use Firefox as my primary browser. 

**Where did it happen?**
It occured on cryptpad.fr

**To Reproduce**
1. Open your cryptpad doc
2. Try selecting text for formatting

**Expected behavior**
Unable to do text selection, for formatting, like Bold, italics, color etc.

**Browser (please complete the following information):**
 - OS: [android]
 - Browser [firefox]
   - variations [e.g. Firefox]
 - Version [88.1.4]
 - Extensions installed (UBlock Origin, decentralyse]
 - Browser tweaks [firefox "Enhanced Tracking Protection" is turned OFF]

**Smartphone (please complete the following information):**
 - Device: [Realme Narzo 10a]
 - OS: [10]
 - Browser [firefox]
 - Version [88.1.4]

**Comment by yurkobb** [comment] 2022-06-25 12:10
...not only for formatting, but for editing in general (copy/cut/paste, etc).

My guess is that the long press triggers right click behavior which blocks doing selection.

**Comment by mthld** [comment] 2022-08-08 09:37
I definitely cannot reproduce this issue on iOS, is it still happening on your Android device?

**Comment by amconners** [comment] 2022-08-22 07:16
I'm able to reproduce this on Android, but I've also found a workaround:

1. If you have a pop up menu or cursor menu open, tap elsewhere in the document to dismiss it.
2. Close the on-screen keyboard.
3. If the word you want to select is behind where your keyboard appears, scroll until it's in a position where the keyboard won't cover it.
4. With the keyboard closed and no menu open, double-tap to select should work consistently. 

Screenshots showing the workaround:

Start:
![Screenshot_20220822-024554_Fennec](https://user-images.githubusercontent.com/22965575/185858865-a5835622-ad43-4ee2-ba3c-f44b7f24bba5.png) 

Dismiss the menu:
![Screenshot_20220822-024602_Fennec](https://user-images.githubusercontent.com/22965575/185858857-c0ea275a-c3af-4737-ad81-b50cc21651b7.png)

Close the on-screen keyboard:
![Screenshot_20220822-024608_Fennec](https://user-images.githubusercontent.com/22965575/185858846-e581e30d-280e-4c6c-8476-0fc8a4b73551.png)


Double-tap to select:
![Screenshot_20220822-024615_Fennec](https://user-images.githubusercontent.com/22965575/185858826-439c01bf-eaab-4358-a31e-25910387a11d.png)

I'm running Fennec F-Droid 103.1.0 on a Pixel 4a with LineageOS 19.1. uBlock Origin, Privacy Badger, HTTPS Everywhere, NoScript, Decentraleyes, and Video Background Play Fix are all installed in the browser (with NoScript set to allow cryptpad.fr and cryptpad.info), but both the issue and the workaround occur with the addons disabled.

**Comment by mthld** [comment] 2022-10-18 09:59
Oops I've missed this one #631, closing this one as duplicate in favor of the other.

**Closed by mthld** 2022-10-18 09:59 UTC
Labels: Bug, Mobile support, Rich Text, Android
