### ISSUE TITLE
Mouse scrolling moves too much

### ISSUE THREAD

**Issue by bremby** [xwiki-labs/cryptpad#803] opened 2021-10-05 20:31 UTC
**Describe the bug**
When I have a spreadsheet open and scroll with my mouse, the view moves too many lines. Initially I can see lines 1-26, but when my mouse wheel makes a single "click" when scrolling down, I then see lines 37-62. Somehow I cannot reach lines 27-36 when using my mouse wheel, I can reach those lines only when scrolling manually with the vertical scrollbar. Scrolling horizontally by holding Shift scrolls just fine. Rich Text files behave as expected, scrolling smoothly. Note that my mouse wheel itself physically moves in steps, but those steps never make any similar behavior outside of cryptpad's spreadsheets.

**Where did it happen?**
This is happening on cryptpad.fr.

**To Reproduce**
1. Open a new spreadsheet.
2. Scroll down with mouse wheel the smallest amount you can.

**Expected behavior**
I expect similar behavior like with the Rich Text files, i.e. scrolling smoothly.

**Browser (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox
 - Version: 89.0.2
 - Extensions installed: UBlock Origin, Cookie Autodelete

Let me know if there's anything else that I could add. Given how annoying this is, surely I must be the only one experiencing this, otherwise this would've been fixed already. :(

**Comment by mthld** [comment] 2022-08-05 12:37
Hello,

As I can't reproduce this issue, is still happening to you?
Maybe it has something to do with your web browser settings, or your operating system ones?

**Comment by bremby** [comment] 2022-08-05 14:20
Hi,
I was wondering the same thing, but I didn't figure it out. However, it's not an issue anymore, now it scrolls as expected. You can close the issue.

These issues are the best, right? Leave them to rot, and they will autoresolve. :D

Cheers! :)

**Comment by mthld** [comment] 2022-08-05 14:25
Glad to know it's working as intended for you too now!

> These issues are the best, right? Leave them to rot, and they will autoresolve. :D

Not our intend here, we've been sadly understaffed for many years. I myself joined the team a few days ago, so it'll probably helps in the future. In the meantime, don't hesitate to help us: https://docs.cryptpad.fr/en/how_to_contribute.html#how-to-contribute

Closing this issue now. :)

**Closed by mthld** 2022-08-05 14:25 UTC
Labels: Spreadsheet
